### ISSUE TITLE
CSRF prevention for non-GraphQL requests?

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1081]
In https://github.com/apollographql/router/pull/1060 I imported and adapted CSRF docs from https://www.apollographql.com/docs/apollo-server/security/cors/#preventing-cross-site-request-forgery-csrf, but removed this paragraph since I was unsure:

> CSRF prevention is only applied to requests that will execute GraphQL operations, not to requests that would load [landing pages](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages) or run [health checks](https://www.apollographql.com/docs/apollo-server/monitoring/health-checks).)

* Is this the behavior we want for the router?
* Is this the behavior we have? I don’t see a corresponding `if` in the plugin code. Should we add it?

**Comment by o0Ignition0o** [comment]
That's an interesting one, i guess it depends because some plugin devs might want to say show a dashboard on a browser or something else, We might have a safe default such as "csrf is enabled on any endpoint" yet allow plugin devs to unsafely remove it?

This imo isnt urgent however

**Comment by glasser** [comment]
You definitely should not apply CSRF prevention to landing pages :) The idea behind CSRF prevention is that it specifically blocks requests that look like "normal web navigation requests" — the whole reason that "simple requests" are not preflighted is that they are the kind of requests you can make people make by clicking links, etc.  So if you CSRF-prevent the landing page, you will have broken the landing page and it will not load :)

Re health checks, note that we're actually removing built-in health checks from AS4 because it is a pretty questionable feature (why not just run a no-op `{__typename}` query, which will check that the actual GraphQL engine is working?). Looking at the feature you have now, I think it is fine to not apply CSRF prevention here. CSRF prevention is about preventing requests with side effects and about preventing things like timing attacks; the health check endpoint shouldn't fall into this category, and enabling CSRF prevention for it will just make the health check feature harder to use by requiring the system that's sending health checks to add extra headers.

Sorry for not asking about this while reviewing the plugin!
