### ISSUE TITLE
API 1.0 - Request/Response mutability.

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1141]
Some of our datastructures have arcs in them.

* Router - RouterRequest, RouterResponse
* QueryPlanning - QueryPlannerRequest, QueryPlannerResponse
* Execution - ExecutionRequest, ExecutionResponse
* Subgraph - SubgraphRequest, SubgraphResponse

This may make sense, as after data from a datastructure has been used by the router then having it as read-only is OK.

Let's revisit each data structure and make sure we're consistent.

**Comment by garypen** [comment]
I noted three `Arc` in the various Request/Response structures:

1. Arc<QueryPlan> in QueryPlannerResponse and ExecutionRequest (query_plan)
2. Arc<Object> in Request (variables)
3. Arc<http_compat::Request<Request>> in SubgraphRequest (originating_request)

I've done some investigation and concluded:

1. We can remove this. The change is quite intrusive and may have a performance impact due to a lot of cloning now being required. The existing code reduces this since an Arc clone is fairly cheap. Advantage, QueryPlans can now be edited.
2. We can remove this. The change is small and impact is likely to be light since cloning doesn't happen much: If we create a debug span or when we first create the pipeline.
3. We should retain this. Arguably, we should maybe only allow originating_request mutation in the router request step and then freeze thereafter.

I've put together a draft PR as a discussion point: #1235

**Comment by garypen** [comment]
Discussion from the draft PR:

https://github.com/apollographql/router/pull/1235#issuecomment-1155354255
https://github.com/apollographql/router/pull/1235#issuecomment-1155366363

Summary: Only make change (2).
