### ISSUE TITLE
API 1.0 - http_compat revisit

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1147]
Http compat was created because the http crate apis are somewhat difficult to use, and also we use the request sometimes when we need to cache, e.g. for dedupe.

However, it's actually debatable that a request in it's entirety should ever be used as a cache key. Let's just make sure we're doing the right thing here as there will be no going back.

**Comment by garypen** [comment]
Some thoughts. Take a look at PR: #1291

Pros:
 - We control the ways in which Requests (in particular) are built
   (e.g.: buildstructor and require URI and method on new)
 - We have types so we avoid the Orphan Rule for implementing IntoResponse
   (for example) to help out with Axum responses
 - We do need to clone without Arc, to support mods and interior mutability
   is fiddly, so perhaps good.

Cons:
 - Another module with potentially confusing naming. Maybe better names
   as http_addon or http_ext or http_extension or ...
 - Implementation is brittle. For instance HeaderValue iteration ordering
   or the fact that we don't clone Extensions when cloning.
 - Some of the code is there to support testing, but we can't mark it
   #[cfg(test)] because of integration tests or interactions with
   buildstructor.

Possible Improvements:
 - We could remove some of the implementation of from_parts(), into_parts(),
   etc and replace that with From implementations which just convert.

On the whole I think we should:
 - Keep it
 - Rename it
 - Try to reduce duplicating code by removing (into_parts(), etc..) and using From.
