### ISSUE TITLE
startup blocks w/ double quotes in block comment 

### ISSUE THREAD

**Issue by sjungling** [apollographql/router#121]
**Describe the bug**
Router fails to start or emit anything to logs (even on trace) when the supergraph contains a multiline comment block that contains double quotes. Can reproduce following the Quickstart guide

**To Reproduce**
1. Installed `router@0.1.0-alpha.0` 
2. Run `curl -sSL https://supergraph.demo.starstuff.dev/ > supergraph-schema.graphql`
3. Edit `supergraph-schema.graphql` to inject the following comment into the `Product` type

```graphql
  """
  **Example**: "Saturn5"
  """
  name: String @join__field(graph: PRODUCTS)
``` 

4. Run `./router --log trace --supergraph supergraph-schema.graphql`
5. Observe that command does not die but also does not start nor log anything to the console
6. To additionally narrow the scope, use single-quotes instead of double-quotes

```graphql
  """
  **Example**: 'Saturn5'
  """
  name: String @join__field(graph: PRODUCTS)
``` 

7. Run `./router --log trace --supergraph supergraph-schema.graphql`
8. Observe `router` successfully starting

**Expected behavior**
Expect the router to start and an output stating that it's now available on `http://localhost:4000`

**Output**
If applicable, add output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 12.0.1

**Additional context**
 - `router 0.1.0-alpha.0`

**Comment by abernix** [comment]
Thanks for reporting this! I can confirm this happens and reproduce — appreciate the instructions!

I believe the actual bug here lives in [`apollo-rs`](https://github.com/apollographql/apollo-rs) which we use for schema parsing.

There's a partial improvement in the latest version (https://github.com/apollographql/apollo-rs/commit/6ab49d2b2e8801f0c6559fefd1a303bfd814ff3e) of it which we haven't bumped to yet — but I've confirmed locally.  In particular, instead of freezing, it now produces:

```bash
Nov 10 21:49:21.184 ERROR apollo_router: Failed to read schema: Could not read schema: Parsing error(s).
Nov 10 21:49:21.184  INFO router: Starting Apollo Router
Nov 10 21:49:21.185  INFO router: Stopped with error
Nov 10 21:49:21.185 ERROR router: Schema was not supplied.
Error: Schema was not supplied.
```

... and it exits. (A good thing, rather than sitting there!)

Of course, this doesn't completely solve the fact that it's perfectly valid for a comment to be placed there.  Anyhow, we'll get this fixed.  Thanks again for reporting!

cc @lrlna

**Comment by o0Ignition0o** [comment]
Hey!

Now that #131 has been merged, this issue should be fixed.

Could you please give it a try and confirm?

Thanks!

**Comment by sjungling** [comment]
> Hey!
> 
> Now that #131 has been merged, this issue should be fixed.
> 
> Could you please give it a try and confirm?
> 
> Thanks!

@o0Ignition0o pulled latest changes and manually injected multi-line commends with `"` into both the `local.graphql` and `supergraph.graphql`. Can confirm I was able to start `router` with both successfully. 🎉

**Comment by o0Ignition0o** [comment]
This is great news! 🎉 closing the issue!
