### ISSUE TITLE
Filter Schema

### ISSUE THREAD

**Issue by bizzi-vinhvo** [apollographql/router#1288]
**Is your feature request related to a problem? Please describe.**
I need to exclude some query/mutation when merge in supergraph

**Describe the solution you'd like**
Look like this article:
https://www.graphql-mesh.com/docs/transforms/filter-schema

**Comment by BrynCooke** [comment]
Does https://www.apollographql.com/docs/studio/contracts/ fit our requirements?

**Comment by abernix** [comment]
Currently, the feature is only for the Enterprise teams, yes.  Contracts will continue to be our suggestion for this for the time-being as we've only recently taken the Contracts feature to GA (in May of this year), and we're working with its adopters to ensure success in their graph filtering.

It's worth pointing out that filtering a supergraph has a lot of considerations to make to do it safely and we've invested a lot of time in that feature the tooling in Studio to make it a really safe experience.  We're continuing to improve the product, and we'll consider ways to bring it to other teams, too.

You are still more than welcome to apply your own filtering to the Supergraph file, but you'd need to do that on the output of, for example, [`rover supergraph compose`](https://www.apollographql.com/docs/rover/commands/supergraphs/).  The Router will merely operate on the supergraph that you pass in and you're more than welcome to filter it, or alter the supergraph if you feel equipped with the right knowledge and tooling to do so.

We'll continue to make this a better experience for everyone as we develop out the product ourselves.  The audience that the tooling is available may certainly change over time as we do that.  I'll close this issue because, even if we do change who can use Contracts, it's likely that the best place to expose that tooling will continue to be in other parts of the platform — rather than in the Router itself — which will continue to operate on the supergraph document itself (which is why it's okay for you to filter it yourself!).

Thanks for raising this originally!
