### ISSUE TITLE
set up the Minimum Supported Rust Version

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1312]
Since the router is usable as a library, we should:
- find out which minimal Rust version we can build the router on
- which minimal Rust version we want the router to build on
- set up a CI pass to guarantee it
- add a badge in the README

**Comment by SimonSapin** [comment]
We already have `rust-toolchain.toml` that makes CI use a fixed toolchain version (1.61.0 today) rather than the Stable channel (though see https://github.com/apollographql/router/issues/1313). I agree it would be good to choose and document a policy for when we can change that version. As long as the router is in 0.x I think bumping whenever is fine. For 1.0+, we should what constraints our users might or might not have.

Finding what minimum version happens to compile today is mildly interesting but I feel that keeping it as low as possible should not be a goal for its own sake.
