### ISSUE TITLE
Context not updated from error in subgraph 

### ISSUE THREAD

**Issue by xsoufiane** [apollographql/router#1335]
**Describe the bug**
I'm trying to insert an entry to the context in a subgraph error, something like this:
```
.map_result(|result: Result<SubgraphResponse, BoxError>| match result {
                Err(err) => {
                    if let Some(fetch_err) = err.downcast_ref::<FetchError>() {
                        match fetch_err {
                            FetchError::SubrequestHttpError { service: _, reason } => {
                                if reason.contains("\"statusCode\":401") {
                                    let res = http::Response::builder()
                                        .status(StatusCode::from_u16(200).unwrap())
                                        .body(fetch_err.to_response())
                                        .expect("Issue serializing fetch error");

                                    let context = Context::new();
                                    let _ = context
                                        .insert::<&str, String>("status-code", "401".into())
                                        .unwrap();

                                    let res =
                                        SubgraphResponse::new_from_response(res.into(), context);

                                    info!("response: {:?}", res);
                                    Ok(res)
                                } else {
                                    Err(err)
                                }
                            }
                            _ => Err(err),
                        }
                    } else {
                        Err(err)
                    }
                }
                other => other,
            })
```
The subgraph response becomes: 
![image](https://user-images.githubusercontent.com/21281785/176884098-a2cfb5ee-f4fb-4738-9f96-e7cac36921b5.png)
I can see the entry but in the router_service part, it's absent:
![image](https://user-images.githubusercontent.com/21281785/176884317-7fb6aa58-e22b-4792-9c28-5a43aba6afd2.png)

Another point, when I insert a new entry in a subgraph response that is Ok, I'm able to see it in the router_service. I suspect that this is an issue only when the errors field is not empty.

**Expected behavior**
we should be able to see new entry in the route_service map_response part.

**Comment by Geal** [comment]
thanks, I'll look into it

**Comment by xsoufiane** [comment]
is there any change on this 🤔 🙏  with the 0.16.0 of the router, are we able to update context now from the map_result

**Comment by garypen** [comment]
I think this is actually down to the same kind of problem as #1284. Namely, any subgraph response isn't preserved through the chain of execution and supergraph response.

Until we resolve #1284 (which is no longer well titled. It's been about header propagation for most users, but this issue shows that it's really about response propagation) this isn't going to be possible as written.

I think an alternative approach would work though. Something like:
```
            .map_result(move |result: Result<subgraph::Response, BoxError>| {
                match result {
                    Ok(v) => {
                        v.context.insert("status-code", "401".to_string());
                        Ok(v)
                    }
                    Err(err) => Err(err),
                }
            })
```
Note: I'm not replicating the logic or dealing with the result of insert failing (might be better to use upsert depending on your use case). The main point is that I'm manipulating the context of the existing response rather than creating a new response and context. You can do this from map_result() or map_response() or any transform that delivers up a Response to work with.

Note: I've updated the names of the various components to match latest naming as we close in on 1.0.

I've confirmed that with this approach changes to the response context are propagated to the supergraph_service().
