### ISSUE TITLE
provide access to the schema in customisation plugins

### ISSUE THREAD

**Issue by garypen** [apollographql/router#1415]
In order to unblock customers requiring access to the schema (supergraph and api_schema) during plugin processing we need to change the various Request signatures to provide shared, read-only access to the schema currently in use in the router.

### Decisions

- [x] Format for sharing.

Consider sharing as an AST document. This is a parsed representation of the schema which means that it doesn't need to be re-parsed on each call to a plugin and could form the basis of a compiler context. I don't think that sharing the existing `Schema` structure is the correct idea since we already know we'd like to evolve/replace this with functionality from the `apollo-rs` compiler.

Decision: Seems like compiler context is the best thing to share.

- [x] How modify `apollo-rs` tooling to support this?

It will require work in `apollo-rs` to support this requirement. How can we do this most efficiently?

Decision: Since a compiler crate will be available soon, we will implement the router API against the first version of that crate. I anticipate doing this during the week commencing 25th July.

**Comment by lrlna** [comment]
I would like to propose that you share the context created by `apollo-compiler`. To fully take advantage of the context and the relationships it creates it's best to combine both the query and the schema. The API to compiler's context makes it _significantly_ easier to query both the schema and the executable (operations, fragments) types, especially when it comes to finding type information in a given operation. While working with the AST is obviously doable, I firmly believe that working with the context will make for a better user experience. If anyone really really prefers to do the hard work and walk the AST, the compiler provides access to the AST it creates as well through its context (which like everything else in the compiler is memoised).

**Comment by lennyburdette** [comment]
:+1: to everything so far. I definitely prefer the compiler API over the AST documents.

I'm not totally clear on how the broadcast mechanism would work, but I'm all for having plugins opt-in to this behavior rather than add more API to the request objects.

How possible is something like this?
* Each time the supergraph updates (via hot reloading or Uplink), the router generates a compiler context and broadcasts it to interested plugins.
* Plugins are able to derive a new compiler context by "adding" the operation document to the supergraph compiler context. This way plugins avoid re-parsing the supergraph. (Though if multiple plugins have to create their own new compiler contexts with the operation, is that wasteful/redundant work?)

**Comment by garypen** [comment]
Additional Notes: It turned out to be expedient to provide the Supergraph Schema as a string for now. When the following improvements are available in apollo-rs:
 - `ApolloCompiler` is `Send`
 - `ApolloCompiler` supports "progressive compiling of Schema + Operation
we'll revisit this and update the API to be more efficient.
