### ISSUE TITLE
yml configuration: CORS - CSRF

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#1483]
Let's have a look at the CORS / CSRF yml configuration, and see if we can nest the csrf configuration within cors.

**Comment by SimonSapin** [comment]
The current structure is:

```yaml
server:
    cors:
        # …
csrf:
    # …
```

The current structure happened because CSRF is a plugin whereas CORS is a layer, but be could change that. Let’s first decide what structure we want and then figure out a way to make it happen.

The options are:

1. Move `csrf` to within `cors`
2. Or move `cors` to the top-level, outside of (next to) `server`
3. Or both of the above
4. Or none of the above

**Comment by garypen** [comment]
@o0Ignition0o Can you provide some motivation as to why "nesting csrf configuration within cors" is a "good thing"? Also, if you do, could you indicate which of the options outlined by Simon seem preferable?

Without that motivation, I'm inclined to think that (4) is the right option.

**Comment by o0Ignition0o** [comment]
CSRF is a way to make sure received requests will have made it through the CORS dance if they were sent from a browser.
This leads me to think CSRF has no reason to live on its own. but its a weakly held opinion.

**Comment by abernix** [comment]
I think having `cors` and `csrf` at the **same** level (along-side) makes the most sense (which I think is number 4?)

I seem to recall from my time working in Ruby on Rails that the notion of CSRF protection existed in dependently from CORS — that is to say, it offered a way to offer cross-site request forgery stuff for your plain-old `<form>` (`application/x-www-form-urlencoded`, or whatever it was).  In fact, it may have pre-dated the solidification of lots of what we (try to 😄 ) understand to be CORS today.

With that in mind, it might not make sense to nest them as they are distinct concepts even if they're closely coupled in our own usage.  Give [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) a read.

**Comment by abernix** [comment]
I don't have a preference for inside `server` or not but the things we already have in `server` lead me to believe it should be in there.

I suppose, if it's easier in one place or the other we can probably figure out how to move it later we can.

**Comment by SimonSapin** [comment]
Having `csrf` config under `server` is tricky for us because at the moment it's technically a plugin. But that should be a weak criteria compared to what makes sense to users IMO.

**Comment by garypen** [comment]
Because of the ways in which plugin configuration, jsonschema and server configuration interact, it's very difficult to have a configuration which looks like:
```
server:
    cors:
        #...
    csrf:
        #...
```
because this would require special treatment of the csrf plugin to "migrate" its configuration from the "plugin" location (which is implicit for apollo_plugins) into the "server" location.

It's more viable to hoist cors to the top level, so:
```
server:
    #...
cors:
   #...
csrf:
   #...
```
is a relatively small change. I'm not convinced that we should do it though, because all the other layers are consistently grabbing their configuration from the `server` "location" and it now seems odd to have `cors` be the only layer which isn't.

Until we decide to fix the main configuration issue: #1454 , I really think we shouldn't do this.

I've got a draft PR: #1586

**Comment by SimonSapin** [comment]
cors being a layer while csrf being a plugin is something our users shouldn't need to care about IMO

**Comment by garypen** [comment]
I agree, but I don't think that's what this is about. We've (previously) decided to put all apollo plugin related configuration in a certain location (at the top level) and all non-plugin configuration is located under `server`. I don't think handling `cors` is such a special case that it justifies changing this decision ahead of any reworking that we will do as part of #1500.

**Comment by SimonSapin** [comment]
We’ve decided not to change configuration for 1.0. Closing for https://github.com/apollographql/router/issues/1500 which encompasses this

**Comment by garypen** [comment]
Re-opening since we've decided to move `cors` to the top level of configuration.
