### ISSUE TITLE
Remove Plugin::activate?

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1549]
Since https://github.com/apollographql/router/pull/1463 no plugin implements the `activate` method. Is it still useful, or can every plugin manage with doing its initialization in `new`? If we remove it for 1.0, we’ll still have the option of adding it back in 1.x if needed.

@BrynCooke wanted to have a look at why it was added in the first place

**Comment by BrynCooke** [comment]
Its useful if a plugin has to interact with a global.

The issue is that if a plugin interacts with a global during construction then there is no way to recover if a subsequent plugin fails.

Unlike the other plugin callbacks activate is infallible, so interaction with globals at this point is safe.

I would not bank on hot reload for telemetry staying out forever, and I can imagine that there will be other situations where interactions with globals may be necessary.

**Comment by garypen** [comment]
Those are arguments for why we might need it in the future though and, as @SimonSapin noted, it's easy to make compatible additions. I'd favour removing it until we need it.

**Comment by BrynCooke** [comment]
I was thinking more about users which are trying to interact with their own client libraries rather than us. I agree we don't have a usecase right now, but lifecycle of other libraries won't necessarily follow our plugins. Agree we can remove and wait for user to ask for it though.
