### ISSUE TITLE
Mark the query plan as pub(crate) in ExecutionRequest

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1558]
Right now, a plugin could replace the query plan in `ExecutionRequest` because it is `pub`

https://github.com/apollographql/router/blob/main/apollo-router/src/services/mod.rs#L603

**Comment by Geal** [comment]
after verification:

`ExecutionRequest` does contain the query plan as a public element:

```rust
pub struct ExecutionRequest {
    /// Original request to the Router.
    pub originating_request: http_ext::Request<Request>,
    pub query_plan: Arc<QueryPlan>,
    pub context: Context,
}
```

But `QueryPlan` cannot be constructed directly in a plugin because the `PlanNode` field is `pub(crate)`:

```rust
pub struct QueryPlan {
    pub usage_reporting: UsageReporting,
    pub(crate) root: PlanNode,
    options: QueryPlanOptions,
}

#[buildstructor::buildstructor]
impl QueryPlan {
    #[builder]
    pub(crate) fn fake_new(
        root: Option<PlanNode>,
        usage_reporting: Option<UsageReporting>,
    ) -> Self {
        Self {
            usage_reporting: usage_reporting.unwrap_or_else(|| UsageReporting {
                stats_report_key: "this is a test report key".to_string(),
                referenced_fields_by_type: Default::default(),
            }),
            root: root.unwrap_or_else(|| PlanNode::Sequence { nodes: Vec::new() }),
            options: QueryPlanOptions::default(),
        }
    }
}
```

It might be useful to add a getter for the `PlanNode` though?

**Comment by o0Ignition0o** [comment]
The trick we had is that plan_node implements serialize, which is enough for dumping purposes, but we could add a getter

**Comment by SimonSapin** [comment]
What do we want plugins to be able or not able to do with the query plan?

Let’s answer that first, then find a way to make it happen in the API.

**Comment by o0Ignition0o** [comment]
I think we want users to be able to dump it for debugging purposes. that's it

**Comment by SimonSapin** [comment]
`QueryPlan` already implements `Debug`. It’s derived so it might not be pretty, but it exists.

There’s also `pub fn contains_mutations(&self) -> bool` which seems fine to me.

Should this issue be closed as done?

**Comment by EXPEylazzari** [comment]
Hi! 

Would you be willing to re-open this issue to add getters for the individual fields of the `QueryPlan` plan so that plugin authors can choose what they want to dump about it?

As mentioned above, it's not pretty, and it's quite verbose. I would have liked to be able to only log the `QueryPlan.formatted_query_plan` field for instance. It seems harmless to add getters that would allow plugin authors to access individual fields.

Thanks for considering it!

**Comment by SimonSapin** [comment]
Hi! Close issues are not a great place for new comments. They tend to get ignored: since they’re closed we expect there’s nothing more to do there. Consider filing a new issue explaining what you’re trying to do. Like, do you have specific things in mind behind "for instance"? Is this only for logging?

**Comment by EXPEylazzari** [comment]
Hi @SimonSapin . Thanks for the reply! I filed a separate issue as suggested: #2707. Hopefully the details are clear. But yes, it would be strictly for logging purposes. Thank you!
