### ISSUE TITLE
supergraph-demo smoke test 7 fails on router 0.16

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1584]
https://github.com/apollographql/supergraph-demo-fed2/pull/212/checks#step:10:165

**Comment by Geal** [comment]
a bisect points to fa0323e4d0b0450b30fdbf4f3cede0ce7d3b655b

**Comment by Geal** [comment]
related to https://github.com/apollographql/federation/pull/2093

**Comment by pcmanus** [comment]
Just to update that the fix for this just got committed and will be part of federation 2.1.0 which should be published later today or tomorrow.

But @Geal, calling your attention on the fact that this PR also changes the name of the config passed to the query planner (from `deferStreamSupport: { enableDefer: true }}` to `incrementalDelivery: { enabledDefer: true }}`), so this will have to be updated in the router at the same time than the new dependency is incorporated.

**Comment by abernix** [comment]
This should be fixed with the `router-bridge` update that is coming soon: https://github.com/apollographql/federation-rs/pull/161
