### ISSUE TITLE
Defer: send the multipart boundary at the end of each part instead of at the beginning?

### ISSUE THREAD

**Issue by BoD** [apollographql/router#1588]
Currently, parts are sent like this:

#### 1st part
```
--graphql
content-type: application/json

(some json)
```

#### 2nd part
```
--graphql
content-type: application/json

(some json)
```

#### last part
```
--graphql
content-type: application/json

(some json)
--graphql--
```

Would it be possible to send them like this:

#### 1st part
```
--graphql
content-type: application/json

(some json)
--graphql
```

#### 2nd part
```
content-type: application/json

(some json)
--graphql
```

#### last part
```
content-type: application/json

(some json)
--graphql--
```

Reason I'm asking: on the client side this would ease the process of detecting that a part has been fully received and that it is time to parse it / surface it. 

With the current format, after receiving the bytes in the first chunk(s) without the delimiter, the client doesn't know if more bytes are coming, and thus must wait for the delimiter - which will come in the next chunks, possibly after a while.

**Comment by abernix** [comment]
Is this related to https://github.com/apollographql/router/issues/1575?

**Comment by Geal** [comment]
not related to #1575. I'll look into doing that, it makes sense to avoid reparsing on every chunk

**Comment by glasser** [comment]
Yes, you definitely should send boundaries at the end of parts instead of at the beginning (in addition to the boundary at the very beginning — which BTW should have a leading CRLF). Otherwise clients using a standard multipart parser (ie, not assuming that the part bodies must contain exactly one line) will hang and not parse the chunk.

Note btw that there need not be any correlation between transfer-encoding chunked chunks and multipart/mixed submessages.

**Comment by glasser** [comment]
Note btw that this means you need to look into the object itself to see if it has `hasNext: true` or false to know which kind of boundary to send, which is awkward but that's the protocol as specified!
