### ISSUE TITLE
Pass in pre-generated query plan directly to router

### ISSUE THREAD

**Issue by maaad-epsilon** [apollographql/router#1757]
**Is your feature request related to a problem? Please describe.**
I would like to persist generated query plans in a datastore like Redis and pass them directly to the router to execute. I haven't been able to find relevant documentation so unsure if this already exists. Seems like a valid use case that should exist.

**Describe the solution you'd like**
A way to pass in a query plan as an argument into the router via plugin or some entry point.

**Describe alternatives you've considered**
The in-process cache for query plans is adequate, but it would be nicer if query plan caching could be handled externally. 

There's also APQ which the router supports, but according to docs, it [does not support external caching yet](https://www.apollographql.com/docs/router/configuration/overview/#automatic-persisted-queries-apq). If there's a way to pass in plain query strings to the router, that would also suffice, but I have not seen documentation on that.

**Additional context**
n/a

**Comment by abernix** [comment]
Could you elaborate on _why_ you want to persist generated query plans in a Redis data store?  What problem are you trying to solve? 

Query plans are tied to schemas so their validity is bounded by the schema they're made against.  We could key the caches accordingly, but it's something that needs to be considered and handled carefully.  Furthermore, query plans tend to range from very small to very large (depending on the complexity of the operation being executed) and our experience with importing them from an external data store is that it's faster to calculate them in-process rather than read them over the network and then deserializing and hydrating them into memory.  (We have tried before and it wasn't a net-win and didn't improve performance when we tested it in our lab which is why we never shipped it in Apollo Gateway's https://github.com/apollographql/federation/pull/171).

---

As for externalizing the APQ cache — external caching for APQ is tracked in #1401.  We agree that makes a lot of sense!  In the future, please open one feature request per issue instead of putting — for example — the APQ request inside of the pre-generated query plan request.  Thanks!

**Comment by maaad-epsilon** [comment]
I'm mainly concerned about the performance of very large queries which is why I wanted to cache the query plans. But you raise good points, and I'm convinced now that I need to rethink my approach.

Thanks for the in-depth explanation.
