### ISSUE TITLE
router needs a timeout for delegated fetch operations

### ISSUE THREAD

**Issue by garypen** [apollographql/router#1984]
At various points we use work deduplication to avoid performing expensive (slow, compute-intensive, potentially flaky) tasks in the router. We need a mechanism to ensure that tasks which are waiting for delegated results to arrive don't wait forever.

This should be a configurable (at least internally in the code, perhaps not as exposed configuration) timeout to allow for different settings for different use-cases.

**Comment by longzheng** [comment]
Just leaving a note that I think I encountered this on one of our production instances of Apollo Router 1.2.0 (before the fix was merged in 1.3.0).

What we observed was that one specific query would never return from the server (or a very long time at least over 5 minutes).

Simply by changing the query by even adding an empty whitespace which should have no effect would return a result immediately (which confirmed there was nothing wrong with the query or the subgraph or the API it was hitting).

For example the broken query body was

```
    "query": "query testQuery($start: Float, $limit: Float, $name: String) {...}"
```

And by simplying adding a space between `query` and `testQuery` it would work

```
    "query": "query  testQuery($start: Float, $limit: Float, $name: String) {...}"
```

It is my interpretation of query deduplication cache to be keyed by the query as a string, which explains why that one specific query would not return and by simplying modifying the query string worked.

We've since upgraded to 1.4.0 so hopefully we don't encounter this issue again.
