### ISSUE TITLE
Triggering different HTTP status codes from Rhai

### ISSUE THREAD

**Issue by abernix** [apollographql/router#2023]
It would be nice if you could short-circuit a request in Rhai-scripts that didn't trigger a 500 error but something softer like a validation error.

from @lleadbet on Slack.

**Comment by garypen** [comment]
It would be nice, but the problem is in preserving the context from `rhai` back to `rust` where the status code is assigned.

Currently, we don't have any way to distinguish a thrown exception from rhai and so we just translate any exception into an INTERNAL_SERVER_ERROR. 

In principle, rhai is happy to throw any thing as an exception, so we could expose HTTP status codes and allow them to be raised as exceptions. If the exception isn't a valid http STATUS_CODE, then we continue to treat it as an INTERNAL_SERVER_ERROR.

Something like:
```
error_log(`bad data received: ${data}`);
throw 400
```
It might be nicer to actually expose the status codes directly into rhai, so something like:
```
error_log(`bad data received: ${data}`);
throw StatusCode.BAD_REQUEST
```
The downside with the second approach is that it requires a lot more documentation, or at least a link to the documentation for the rust `http` crate. The second approach would probably require more work as well.

Opinions?

**Comment by Meemaw** [comment]
How would be define the message that is raised along with the status code? As long as we can do that somehow (status + message), that works for us.

**Comment by Meemaw** [comment]
`throw (400, "whatever my message is")` would be a great/minimalistic API from the user perspective imho.

**Comment by lleadbet** [comment]
++ to the tuple, would solve for all of my needs as well and it's fairly simple to understand.

**Comment by garypen** [comment]
Ok. If the error isn't a tuple with an integer as the first argument, we'll continue to return INTERNAL_SERVER_ERROR with a message of whatever string representation we could get out of the error. I'll discuss this with team tomorrow.

**Comment by garypen** [comment]
Discussed this in team meeting today. Team decision:
 - we will use numbers to represent http status codes
 - we will use [ObjectMap](https://rhai.rs/book/language/object-maps.html?highlight=objec#object-maps) to implement the functionality
Examples:

```
throw #{
  code: 400,
  message: "my message"
}
```
```
throw #{ 
  "code": 400,
  "message": "my message"
}
```

**Comment by Meemaw** [comment]
@garypen thats great! Looking forward to this feature 🎉
