### ISSUE TITLE
provide explicit metric for internal router latency

### ISSUE THREAD

**Issue by deweyjose** [apollographql/router#2057]
We need the ability to accurately report and attribute latency within our Federated ecosystem to internal Router latency and Subgraph request latency. 

We'd like a prometheus metric designed to capture this explicitly.

We've discussed trying to back out subgraph latency metrics from supergraph latency metrics but issues surrounding truly federated queries across multiple subgraphs can lead to confusing results.

**Comment by Geal** [comment]
The router already tracks this data for every span reported, through the `busy_ns` and`idle_ns` attributes, indicating respectively the time the router actually spends working in that spans, and the time spent waiting for something to happen. The issue here is that there is no way to accurately calculate the latency added by the router, as multiple subgraph requests can happen in parallel, and finding out which one increased the total latency and by how much would be difficult.

I'm not against having a way to estimate the router's overhead, but we would need to be clear about the expectation here, this cannot be a precise metric

**Comment by deweyjose** [comment]
The expectation for us would be an estimate not 100% precision. I think deducting the time spent waiting for the longest subgraph request from the total request time may be a good estimation for what we're looking for.

**Comment by garypen** [comment]
see also: #1949

**Comment by Geal** [comment]
alright, so then do you have a way to extract it from the span or should that be exposed as a prometheus metric?

**Comment by bnjjj** [comment]
First very naive implementation is part of https://github.com/apollographql/router/pull/1970

**Comment by bnjjj** [comment]
Also related to https://github.com/apollographql/router/issues/1949
