### ISSUE TITLE
`@defer` directive should work with mutations

### ISSUE THREAD

**Issue by alessbell** [apollographql/router#2099]
**Describe the bug**
Mutations should also support `@defer`. Given the following mutation:

```graphql
  mutation ($userId: ID!, $paymentInformation: PaymentInformationInput!) {
    makePayment(userId: $userId, paymentInformation: $paymentInformation) {
      id
      ... @defer {
        paymentStatus {
          __typename
          id
          ... on PaymentSuccess {
            billedAmount
          }
          ... on PaymentFailed {
            reason
          }
        }
      }
    }
  }
```
when following the reproduction steps below, the router returns the error `cannot query field 'makePayment' on type 'Query'`. The same mutation returns a multipart response when used with Apollo Server 4.

I've tried several different syntaxes using `@defer` with mutations in the router but always receive an error.

**To Reproduce**
1. Checkout https://github.com/apollographql/router-defer-e2e-tests/pull/15
2. Follow the README instructions to bring up the router and start the front-end dev server
3. Visit http://localhost:3000/purchase, open the network tab and click the "Make Payment" button
4. Observe the error `cannot query field 'makePayment' on type 'Query'`

**Expected behavior**
A multipart response with the fragment marked with `@defer` arriving after the initial chunk.

**Comment by jpvajda** [comment]
@abernix it looks like this issue has a Draft PR, is the plan to deliver this improvement for the upcoming defer GA? We have a related issue on the client to consider for this change. https://github.com/apollographql/apollo-client/issues/10272 cc @alessbell

**Comment by abernix** [comment]
@jpvajda My current understanding is that this issue is actually about _more_ than just mutations — it's actually a more general bug in the execution of the query plan that is being encountered here.  There's a Router-based bug here an I think we may update the title of this issue to reflect more precisely what it is pending a bit more understanding.

The solution here will require that we add a bit of information to our query plans **or** derive the information details another way (ourselves) from the schema/operation.  @Geal is working on a solution to that.

Our intention is to ship this as a bug fix as soon as possible, whenever that is.  Do you expect to require some matching changes on Client-side for this specifically?  My surface-level assessment is that the issue you linked to is not necessarily directly connected to this and perhaps still something that needs fixing, but that you encountered a _different_ error when trying to reproduce this with the Router.  Does that track with you?

**Comment by Geal** [comment]
I think we could merge #2102 first, which fixes this issue, then move on to the larger change in #2109

**Comment by dkogithub** [comment]
Dear Apollo Team, we just started using apollo http link to handle @defer, I'm a bit confused how it works with mutations, as I understood everything get updated when final patch is came, which is a bit breaking the whole idea of @defer, I found this fix which is introduced it https://github.com/apollographql/apollo-client/pull/10368.

Is there any plan to get updated UI patch by patch, to be able to get achievements from defer directive or maybe you can suggest any workaround?

The situation is next - we have a configurator with deferred prices fields and we would like to update UI and give access to user to do the next configuration action before prices come. Pricing is quite complicated and slow in some cases, we would like to do not block the user. 

Can you please advice?

**Comment by alessbell** [comment]
Hi @dkogithub 👋 

The `client.mutate` API in Apollo Client was designed to resolve with a single result, so when adding basic `@defer` support to `client.mutate` in that PR you referenced above which shipped at a patch version, breaking changes were off the table. This meant we'd have to collect the chunks and resolve them once at the end; as you correctly note, this approach doesn't leverage the power of `@defer`.

In sum, this has everything to do with Apollo Client and nothing to do with the Router :) I've gone ahead and created a [feature request](https://github.com/apollographql/apollo-feature-requests/issues/394) you can subscribe to since this will require a more fundamental change to the `client.mutate` API.

Let me know if you have any other questions over on that issue, thanks!

**Comment by dkogithub** [comment]
Hi @alessbell, many thanks for the your quick response and clarification! Glad to hear it's already planned to do, I will follow the feature then, thanks! :)
