### ISSUE TITLE
Set multiple set-cookie headers

### ISSUE THREAD

**Issue by tomfa** [apollographql/router#2211]
**Describe the solution you'd like**
I'd like the ability to set multiple `set-cookie` headers in same response.

[Minimal code demonstrating issue](https://gist.github.com/tomfa/a78954ca5307477e1d5bde3baf2222c3)

**Describe alternatives you've considered**
Removing/reducing use of cookies in my services. For now, this is a blocker for us migrating from @apollo/gateway.

**Additional context**
We are using multiple cookies in one subgraph, relating to auth.

https://github.com/apollographql/router/issues/1284 seem related.

**Comment by garypen** [comment]
There is a bit of an impedance mismatch with `rhai`, `rust` and `header maps` and as you've found it's not possible with our current API to `append` multiple entries to the header map with the same key.

I think the intuitive way to fix this is to use your second syntax, i.e.: retain the existing simplifying approach for single key/value assignments and to add support for accepting an array of values to be interpreted as a HeaderMap append() (rather than an insert()).

This fix is relatively simple and I have a version which works with your example as follows in the abridged curl interaction with my updated router:
```
> POST / HTTP/1.1
> Host: 127.0.0.1:4000
> User-Agent: curl/7.79.1
> Accept: */*
> content-type: application/json
> Content-Length: 48
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< set-cookie: foo=bar; Domain=localhost; Path=/; Expires=Wed, 04 Jan 2023 17:25:27 GMT; HttpOnly; Secure; SameSite=None
< set-cookie: foo2=bar2; Domain=localhost; Path=/; Expires=Wed, 04 Jan 2023 17:25:27 GMT; HttpOnly; Secure; SameSite=None
< vary: origin
< content-type: application/json
```

Let me know what you think about this approach. If you like it, I can get the fix into our next release.

**Comment by a-pedini** [comment]
@garypen sorry for posting on a closed issue but it is relevant I think. Your solution works if you set multiple cookies in the rhai script, but not if multiple cookies come from the subgraph...
I put here my config and script that I'm using for investigation: https://github.com/a-pedini/a-pedini_router/tree/main
but essentially my subgraph apps sets 3 test cookies with this node code:
```
app.use((req: Request, _res: Response, next: NextFunction) => {
    _res.cookie('test_cookie_method_1', '1');
    _res.cookie('test_cookie_method_2', '2');
    _res.cookie('test_cookie_method_3', '3');
    next();
  });
```

The logging in my rhai script can see all three in the response.headers object:
```
Subgraph response headers:x-powered-by: Express
set-cookie: test_cookie_method_1=1; Path=/
set-cookie: test_cookie_method_2=2; Path=/
set-cookie: test_cookie_method_3=3; Path=/
x-correlation-id: test_alex_propagation_and_cookie2
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 306
etag: W/"132-xilK2xBK9cdncPb1kUdPKzRpR4E"
date: Tue, 13 Dec 2022 00:05:40 GMT
```
but when I iterate over the headers in the handler script I get:
```
apollo_router::plugins::rhai: iterator:x-powered-by: Express
apollo_router::plugins::rhai: iterator:set-cookie: test_cookie_method_1=1; Path=/
apollo_router::plugins::rhai: iterator:None: test_cookie_method_2=2; Path=/
apollo_router::plugins::rhai: iterator:None: test_cookie_method_3=3; Path=/
apollo_router::plugins::rhai: iterator:x-correlation-id: test_alex_propagation_and_cookie2
apollo_router::plugins::rhai: iterator:access-control-allow-origin: *
apollo_router::plugins::rhai: iterator:content-type: application/json; charset=utf-8
apollo_router::plugins::rhai: iterator:content-length: 306
apollo_router::plugins::rhai: iterator:etag: W/"132-xilK2xBK9cdncPb1kUdPKzRpR4E"
apollo_router::plugins::rhai: iterator:date: Tue, 13 Dec 2022 00:05:40 GMT
apollo_router::plugins::rhai: iterator:connection: keep-alive
apollo_router::plugins::rhai: iterator:keep-alive: timeout=5
```
the value of the cookies is there but it lost the key, as the iterator key now says None and the result is that when in the script I get the header by value set-cookie I only get the first one and not all three.

When I iterate over them in the supergraph_service handler, I only get the first value:
```
apollo_router::plugins::rhai: Router Response Context -> Client Response header: (set-cookie:test_cookie_method_1=1; Path=/)
apollo_router::plugins::rhai: Router Response Context -> Client Response header: (x-correlation-id:test_alex_propagation_and_cookie2)
```
am I doing something wrong in the script?

**Comment by a-pedini** [comment]
> @garypen sorry for posting on a closed issue but it is relevant I think. Your solution works if you set multiple cookies in the rhai script, but not if multiple cookies come from the subgraph... I put here my config and script that I'm using for investigation: https://github.com/a-pedini/a-pedini_router/tree/main but essentially my subgraph apps sets 3 test cookies with this node code:
> 
> ```
> app.use((req: Request, _res: Response, next: NextFunction) => {
>     _res.cookie('test_cookie_method_1', '1');
>     _res.cookie('test_cookie_method_2', '2');
>     _res.cookie('test_cookie_method_3', '3');
>     next();
>   });
> ```
> 
> The logging in my rhai script can see all three in the response.headers object:
> 
> ```
> Subgraph response headers:x-powered-by: Express
> set-cookie: test_cookie_method_1=1; Path=/
> set-cookie: test_cookie_method_2=2; Path=/
> set-cookie: test_cookie_method_3=3; Path=/
> x-correlation-id: test_alex_propagation_and_cookie2
> access-control-allow-origin: *
> content-type: application/json; charset=utf-8
> content-length: 306
> etag: W/"132-xilK2xBK9cdncPb1kUdPKzRpR4E"
> date: Tue, 13 Dec 2022 00:05:40 GMT
> ```
> 
> but when I iterate over the headers in the handler script I get:
> 
> ```
> apollo_router::plugins::rhai: iterator:x-powered-by: Express
> apollo_router::plugins::rhai: iterator:set-cookie: test_cookie_method_1=1; Path=/
> apollo_router::plugins::rhai: iterator:None: test_cookie_method_2=2; Path=/
> apollo_router::plugins::rhai: iterator:None: test_cookie_method_3=3; Path=/
> apollo_router::plugins::rhai: iterator:x-correlation-id: test_alex_propagation_and_cookie2
> apollo_router::plugins::rhai: iterator:access-control-allow-origin: *
> apollo_router::plugins::rhai: iterator:content-type: application/json; charset=utf-8
> apollo_router::plugins::rhai: iterator:content-length: 306
> apollo_router::plugins::rhai: iterator:etag: W/"132-xilK2xBK9cdncPb1kUdPKzRpR4E"
> apollo_router::plugins::rhai: iterator:date: Tue, 13 Dec 2022 00:05:40 GMT
> apollo_router::plugins::rhai: iterator:connection: keep-alive
> apollo_router::plugins::rhai: iterator:keep-alive: timeout=5
> ```
> 
> the value of the cookies is there but it lost the key, as the iterator key now says None and the result is that when in the script I get the header by value set-cookie I only get the first one and not all three.
> 
> When I iterate over them in the supergraph_service handler, I only get the first value:
> 
> ```
> apollo_router::plugins::rhai: Router Response Context -> Client Response header: (set-cookie:test_cookie_method_1=1; Path=/)
> apollo_router::plugins::rhai: Router Response Context -> Client Response header: (x-correlation-id:test_alex_propagation_and_cookie2)
> ```
> 
> am I doing something wrong in the script?

I forgot to mention... I tried this with both the current release version (which doesn't have your fix), and I also tried compiling the dev branch of the router and using the resulting binary, in both cases I get the same result

**Comment by garypen** [comment]
@a-pedini You are tripping over a few bugs, relating to:

1.  how headers are handled between rhai/rust
2.  how headers are propagated within the router

The first problem is caused by the fact that when adding support for headers to our rhai interface, I made the simplifying assumption that a key would only have one value. I was trying to make rhai coding simpler, but it's a mistake because now there's no easy way to manipulate multiple values on a single key. The bug I fixed made it possible to set multiple values, but I can't compatibly address the access problem, since it would probably result in an incompatible change.

The issue with no names in the iterator appears to be a new problem, but is almost certainly related.

I think I could provide an interface which was compatible which returned a string if there was a single value and an array if there were multiple values. Not sure if that's a good thing to do or not... That would means existing scripts kept working, but it would cause issues for handling in new scripts since you'd now have to decide if you had a string or an array to work with. rhai is a dynamic language, so I guess it's ok to do that, but it feels a bit clunky. Properly fixing this (by always returning an array of header values) requires we wait for a router 2.0 release.

The second problem has some complications and is a [known issue](https://github.com/apollographql/router/issues/1284). This is on our schedule to be worked on early next year.

Summary: I'll raise a new issue to capture the header handling issues within `rhai` and try to find some time to work on that soon. I'll update here with the new issue details.

**Comment by a-pedini** [comment]
> 

@garypen thank you so much for the detailed reply!
I'll discuss internally if we can wait for the 2.0 release before migrating, as we are in the process of migrating from Federation V1 to V2, and we thought we might as well migrate from apollo gateway 3.x to the router.

I think I might have a workaround for the moment, but haven't fully tested it yet.
My idea is that the order of the items in the iterator seems to be guaranteed, so that any consecutive items with None as key, belong to the previous non-None key... so if I iterate over the items and keep track of the latest valid key, I can re-group them together.
at that point, once I have an array in the context matching the same key, I can concatenate the values into a single header with comma separated multiple values and it **should** work 😅 

Thanks again

**Comment by garypen** [comment]
@a-pedini 

Your assumption about `key: None` is correct. It turns out that is behaviour inherited from the underlying rust http crate (see the other issue), so that is "working as intended", although I question if I would have done it that way.

**Comment by a-pedini** [comment]
@garypen thanks a lot for the quick change! I tried the latest dev locally and I can report that you can use the new .values(name) method also for headers that have a single value, it will simply return an array of 1 element.
This makes it very useful for us as we don't have to know before hand if the header is supposed to be an array or not, we can treat them all the same :)

just to share, with this in my rhai script:
```
for header in response.headers {
    print("iterator: "+header.name+"="+header.value+" type:"+type_of(header));
    print("arrayvalue: "+header.name+"="+response.headers.values((header.name+""))+" type:"+type_of(response.headers.values((header.name+""))));
}
```
I'm logging: 
```
apollo_router::plugins::rhai: iterator: x-powered-by=Express type:(core::option::Option<http::header::name::HeaderName>, http::header::value::HeaderValue)
apollo_router::plugins::rhai: arrayvalue: x-powered-by=["Express"] type:array
apollo_router::plugins::rhai: iterator: set-cookie=test_cookie_method_1=1; Path=/ type:(core::option::Option<http::header::name::HeaderName>, http::header::value::HeaderValue)
apollo_router::plugins::rhai: arrayvalue: set-cookie=["test_cookie_method_1=1; Path=/", "test_cookie_method_2=2; Path=/", "test_cookie_method_3=3; Path=/"] type:array
apollo_router::plugins::rhai: iterator: None=test_cookie_method_2=2; Path=/ type:(core::option::Option<http::header::name::HeaderName>, http::header::value::HeaderValue)
apollo_router::plugins::rhai: arrayvalue: None=[] type:array
apollo_router::plugins::rhai: iterator: None=test_cookie_method_3=3; Path=/ type:(core::option::Option<http::header::name::HeaderName>, http::header::value::HeaderValue)
apollo_router::plugins::rhai: arrayvalue: None=[] type:array
apollo_router::plugins::rhai: iterator: x-correlation-id=test_alex_propagation_and_cookie4 type:(core::option::Option<http::header::name::HeaderName>, http::header::value::HeaderValue)
apollo_router::plugins::rhai: arrayvalue: x-correlation-id=["test_alex_propagation_and_cookie4"] type:array
apollo_router::plugins::rhai: iterator: access-control-allow-origin=* type:(core::option::Option<http::header::name::HeaderName>, http::header::value::HeaderValue)
apollo_router::plugins::rhai: arrayvalue: access-control-allow-origin=["*"] type:array
```

so I just need to exclude the ones where header.name = None, and then I can handle all the headers as arrays
