### ISSUE TITLE
Expose schema on endpoint

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#2361]
**Is your feature request related to a problem? Please describe.**
Currently there is no nice way to get a schema that is currently deployed on the server for local development. One would have to use rover cli and know the variant, havi api key and more just to get the schema.

**Describe the solution you'd like**
Add an optional endpoint to expose the schema on e.g. `/graphql.schema` or `/supergraph.graphql`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Geal** [comment]
Did you try to activate introspection? https://www.apollographql.com/docs/router/configuration/overview#introspection

**Comment by Meemaw** [comment]
Hmm, this might work. Tried it with https://github.com/prisma-labs/get-graphql-schema and looks roughly correct. Do you know off/recommend any other tools to generate a GraphQL schema from an (introspection) query?

I have 1 feature request for this though. We want to expose this only if special header is sent, as we don't want to expose our schema publicly. Does that sounds reasonable?

**Comment by abernix** [comment]
You can convert the introspection response to SDL [using `rover graph introspect`](https://www.apollographql.com/docs/rover/commands/graphs/#graph-introspect).

Not wanting to expose your schema publicly makes _a lot_ of sense though, and that's certainly we disable introspection in production environments by default.  We aren't currently planning on introducing any dynamic abilities to the Router itself to toggle on introspection (using headers, auth tokens, etc.) right now because of the size of what that feature area can grow into and our principle that this is better served by a Schema Registry, something we provide as a core feature [in Apollo GraphOS](https://www.apollographql.com/docs/graphos#core-features).  And this becomes even more important when workin with a federated graph with many different subgraphs, and when graphs exist which are derivatives of other graphs (e.g., "admin" graphs).

With the schema stored in the registry, you can both browse the graph in Apollo Studio, see which subgraphs own which fields, the difference between the Supergraph and the API schema, and also provide access to query the graph with full documentation using Apollo Explorer but while keeping introspection safely off on your Router (Even for public API consumers, if you'd like!).  Additionally,  `rover` can give access to your graph in an access-controlled way, using an API token and the [`rover graph fetch` command](https://www.apollographql.com/docs/rover/commands/graphs#graph-fetch) to output the SDL for tooling purposes.

Hope this helps!
