### ISSUE TITLE
Create and expose custom endpoints from a plugin

### ISSUE THREAD

**Issue by consra** [apollographql/router#2461]
**Describe the solution you'd like**
I was unable to find documentation about how to create and expose custom endpoints created in a plugin.

**Additional context**
I want to create a custom health check in a plugin, which will also check the health of a subgraph.

Is there any way I can obtain that ?

**Comment by bnjjj** [comment]
Yes it's not well documented because it's still experimental (the API might change in the future). You should create a rust plugin and implement [this method](https://github.com/apollographql/router/blob/dev/apollo-router/src/plugin/mod.rs#L230:L230) which returns a multimap with a listen address (if you want to listen on a different port) and the `Endpoint` itself (the path on which you want to listen and the `Handler`).

**Comment by abernix** [comment]
I'll close this since we haven't heard back, but let us know if you didn't sort this out.  Thanks!
