### ISSUE TITLE
JWT validation specific to subgraph

### ISSUE THREAD

**Issue by nils-jansen** [apollographql/router#2486]
[Refers to the new experimental jwt validation feature: [https://www.apollographql.com/docs/router/configuration/authn-jwt](https://www.apollographql.com/docs/router/configuration/authn-jwt)]

**Problem description**
While parts of the supergraph should be accessible only with a valid JWT, other parts should be completely public, without the need for jwt Authorization.

**Possible Solution**
The configuration file should allow for a per-subgraph configuration, similar to the [header propagation configuration](https://www.apollographql.com/docs/router/configuration/header-propagation/).

**Comments**
Happy to implement this myself, let me know your thoughts. @garypen you might be the right person to have a look at this :)

**Comment by garypen** [comment]
@nils-jansen I appreciate your offer to get involved, but it's probably a little too soon. This is an active area of research and design and I think it will be volatile for a while yet. I'll update this ticket when things settle down a little so that you get an idea of how things are developing and how we can proceed.
