### ISSUE TITLE
What happens if client cancels the request?

### ISSUE THREAD

**Issue by NoobMaster-96** [apollographql/router#2536]
I wanted to know if the router drops the request when the client terminates it from its end and if we have any metrics which can be used to check the number of dropped requests.

**Comment by Geal** [comment]
if the client drops the request, the router will drop it too, but there's one exception: if query planning was already started, the router will finish that phase and store the result in the cache before dropping the request. This is done because when a query takes a long time to plan and the client timeouts, on the next call with this query it will work.

Tracking dropped requests sounds possible, but does not fit very well in the poll based futures model. Which insight would you derive from this metric?

**Comment by NoobMaster-96** [comment]
Thanks @Geal for the clarification. Can you point to the place in the router repo where we actually drop the request ?

**Comment by Geal** [comment]
Here: https://github.com/apollographql/router/blob/dev/apollo-router/src/axum_factory/listeners.rs#L244
But at this point there's no way to know if the request was canceled

**Comment by Geal** [comment]
I'm closing this now, feel free to reopen for further discussion
