### ISSUE TITLE
Router treats subgraph 4xx responses as errors

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#2687]
This is more of a question, than a bug/issue. Currently router treats subgraph/upstream 4xx responses as errors. Those are logged, and will also mark traces as errors.

This might be fine, as according to spec all responses should be 200. However, a lot of GraphQL servers do not 100% comply to the spec.

A common example of a 400 error from a subgraph is a custom scalar that router does not have enough info about to validate, but the subgraph will reject it in the validation phase.

This will result in a high error rate in router, which makes observability/monitoring/alerting a challenge.

What is your stance on this?

**Comment by Geal** [comment]
We have to follow the specification on this. It would make more sense for the subgraph to return a graphql error (with a 200 status) for this validation, because that can then be integrated with the rest of the response.
With https://github.com/apollographql/router/pull/2524 though, it should be possible to hook at the subgraph service stage. Maybe a `map_error` on the rhai side could make sense too, but we have not looked at that yet

**Comment by BrynCooke** [comment]
Related to #3328

**Comment by abernix** [comment]
I'm going to close this for now.  Thanks for opening it originally, @Meemaw.  We've made a number of changes on this behavior since Feb (see linked issues), but we're happy to continue the discussion if you have new thoughts. (Probably open a GH Discussion to discuss! 😄 )
