### ISSUE TITLE
Q: Is support for native rust plugins for router going away?

### ISSUE THREAD

**Issue by quinnjn** [apollographql/router#2812]
## Description 
I've been actively working on a native rust plugin to use with router which would add custom metrics. Last week, I was referencing this docs link: https://www.apollographql.com/docs/router/customizations/native/#add-custom-metrics. I've noticed that the link is now dead.

It looks like a recent PR (https://github.com/apollographql/router/pull/2775) removed the link. I also see some references to the native rust plugin, and the custom router binary went away in this PR.

I didn't see any mention of native rust plugin support changing in the PR, or any mention on the release changelog. So I'm not to sure what my action should be: continue to develop the rust plugin referencing removed docs or scrap this native rust plugin approach.

Can you provide me with some direction on the support for native rust plugins with router? Should I continue to develop this native rust plugin, or what would you advise?

**Comment by chandrikas** [comment]
Hi @quinnjn, 

Thanks for bringing this up! The short answer is - no, our support for Rust plugins is not going away. However, we do want to focus on building most of the common customisations into our stock router binary (configured through YAML) so that customers don't have to maintain monolithic custom packages of their own. As you may have noticed, we also recommend using Rhai scripting, where appropriate, for lightweight customisations. We've found that many users appreciate the simplicity of using Rhai/YAML versus introducing the Rust toolchain to their build pipelines. For more powerful customizations, the Router now supports [external coprocessors](https://www.apollographql.com/docs/router/customizations/coprocessor/). This provides you with more control over how you want to customize (eg language of your choice, disk/network access) while also ensuring fault isolation.

So should you move away from creating your own plugins? Only if you think your custom use cases are not available as configuration options in our stock router binary. And if they are not, we would love to learn more about what is it that you would like to see so we can bake that functionality directly into the router so others in the community can easily use those features via simple YAML config.

**Comment by abernix** [comment]
Everything @chandrikas remains true and the Rust plugins aren't going away. I'm going to close this as we did restore those docs as they were before.   Thanks for opening this inquisition originally, and I hope you can rest easy knowing that the answer is "no".
