### ISSUE TITLE
Will the rug be pulled out from us if we use this project?

### ISSUE THREAD

**Issue by naxgrp-jfulton** [apollographql/router#2822]
I notice that your documentation is quickly removing references to how to extend the router, though you missed a few spots.  Will the project continue to support plugging capability?  Will we have to pay for the privilege if all we want to do is simply validate a JWT token?  If so, is there a point in continuing to share the code publicly?  Would the community benefit by having a truly open source variant that isn't so crippled as to make GraphQL completely propriety?

**Comment by dobrynin** [comment]
I am trying to upgrade from Apollo Gateway to Apollo Router and I also was surprised to find that handling JWT tokens appears to now only be accessible for enterprise customers. Is that correct? If so that's unfortunately a blocker to switching for us.

**Comment by chandrikas** [comment]
Hey @naxgrp-jfulton - pardon our dust, we're in the process of moving these docs to [crates.io](http://crates.io/) for various reasons, but the Rust plugin API remains supported in the router and that hasn't changed. We'll update the Apollo docs to make this more clear, thanks for your patience as we get this sorted out.

**Comment by abernix** [comment]
This issue is quite old now and was meant to be closed a while ago, but the documentation has had all of the information about the Rust plugins restored to where it was in our existing documentation.  We continue to improve the documentation that lives on Crates.io, but our existing documentation is also still useful in that regard.
