### ISSUE TITLE
Tracing: What do we want to measure and how

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#29]
Followup to a comment, now that we have stable tracing we might wanna sit back and figure out what we would like to trace, and at what level.

IMO this calls for a group discussion, I hope this issue provide such a space.

Do we really need to measure so much? @BrynCooke any opinion on this?

**Comment by abernix** [comment]
This issue is getting a bit stale at this point and i'm not sure if we have anything actionable on it today, particularly given that we've done a lot of measuring (over measuring, in a lot of cases!) in our tracing and have observed — in most cases —  the performance and verbosity implications of doing so.

Do we want to do anything else with this right now, concretely?

**Comment by o0Ignition0o** [comment]
I don't think we do, we have changed this quite a bit over time, so i m closing this.

Happy to reopen later if needs be
