### ISSUE TITLE
Redis connections not closed

### ISSUE THREAD

**Issue by Geal** [apollographql/router#3010]
there's an issue in APQ caching in Redis, where a lot of connections are opened to the Redis cluster but never closed, and this has an impact on performance

**Comment by oliverjumpertz** [comment]
To add more context:

We currently use AWS ElastiCache with Redis engine 6.x for our distributed APQ cache.

We have one primary endpoint configured in our router config.

After restart, open connections rise to ~154 after the following traffic:

Total requests: 588270 (a nightly load test).

After a total of another 587149 requests (another load tests), open connections have risen to 167.

We can observe that sometimes, connections are closed, but that is due to downscaling the router pods again after our nightly load test (we are 99.99% sure that this is the case).

Overall, our graphs show the amount of open connections rising.

From time to time, request times completely break in. Other times, everything is fine.

These are our observations so far.

**Comment by abernix** [comment]
We'll try to pick this up for investigation in the next couple weeks.  This could very well be a bug in our dependency that we use (`fred`), but I'll note that there's a pending dependency update for `fred` pending in #3165 that would at least be checking. 

Suggestion for whoever picks this up: A time-boxed (2 hours?) understanding of where the problem exists and whether it's a dependency fix or something more complex.

**Comment by abernix** [comment]
@oliverjumpertz Is this still impacting you?  I failed to come back to this ticket and update it, but we did update `fred` to the latest version.

**Comment by abernix** [comment]
I'm going to close this, but happy to re-open it if this is still impacting you on the latest version!

**Comment by oliverjumpertz** [comment]
Hey, sorry, the notification somehow went under.

Everything seems fine now on v1.26.X. We can even see connections dropping now.
