### ISSUE TITLE
Enforce plugin ordering for all Apollo plugins

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3230]
We currently have ordering enforced for the following plugins:

- apollo.include_subgraph_errors
- apollo.csrf
- apollo.headers
- apollo.telemetry

After this plugins are executed in a deterministic ordering, but what this is depends on position in yaml.

Let's enforce an ordering for all Apollo plugins. Suggest:
- [ ] Add a test that ensures that all Apollo plugins are covered by the ordering list.
- [ ] Tweak logic such that user plugins can be inserted into the list allowing us to specify that some Apollo plugins are run after the user plugins.

Relates to #3207

**Comment by SimonSapin** [comment]
If all Apollo plugins are to have an enforced ordering, we could refactor the `create_plugins` function to not iterate `config.apollo_plugins` at all, and refer to internal plugins by Rust type path instead of name. That way Apollo plugins wouldn’t need to go through the registry and we wouldn’t need a `name.starts_with("apollo.")` special case.
