### ISSUE TITLE
Feature Request: allow an option to skip TLS validation for subgraph traffic.

### ISSUE THREAD

**Issue by Bjohnson131** [apollographql/router#3246]
**Is your feature request related to a problem? Please describe.**
I'm attempting to test my subgraph locally on my development machine. When I do this, Router will try to validate TLS, and there is no  way to disable this.

**Describe the solution you'd like**
I'd like the option to disable TLS certificate validation and TLS hostname validation (as I can with rover) while the `--dev` flag is specified.

**Describe alternatives you've considered**
Disabling TLS on my services
Modifying router source to remove TLS

**Additional context**
This is a request to mirror rover's option to disable TLS while introspecting graphs into Router's subgraph requesting.

**Comment by Geal** [comment]
What is the issue with TLS validation? Is the subgraph certificate expired, used for the wrong domain or is the development machine missing the certificate authority?

**Comment by Bjohnson131** [comment]
> What is the issue with TLS validation? Is the subgraph certificate expired, used for the wrong domain or is the development machine missing the certificate authority?

There are a few issues,
 - the subgraph wants to enforce TLS.
 - the subgraph provides a TLS certificate that won't work for a development environment
 - the subgraph provides a TLS certificate that isn't for localhost, but for another name completely.
 - downgrading the service to not use TLS will cause the subgraph to misbehave.

**Comment by Geal** [comment]
so if I understand correctly, you have a subgraph software that you want to run locally, that comes prepackaged with a certificate and key that you cannot change, and that certificate is defined for a specific domain that is not localhost.

Right now I'm looking for ways to solve this for you without adding an option to disable validation, because once we do that, the risk of vulnerabilities due to misconfiguration becomes huge.

Further questions:
- isn't there really a way to change the certificate of the subgraph? Or is that certificate and key already hardcoded in there the same that will be used in production?
- can you update your `/etc/hosts` file to point the certificate's domain to localhost?
- can you add the certificate's authority to the trusted list for the router? This can be configured per subgraph: https://www.apollographql.com/docs/router/configuration/overview#tls

**Comment by abernix** [comment]
We'll close this since we haven't heard back from you in a couple months now and we'll assume you've worked around this.  Happy to re-open if this is not the case, and thanks for opening this originally!
