### ISSUE TITLE
Asynchronous External Coprocessor Requests

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#3297]
**Describe the solution you'd like**

The ability to have "fire and forget"/asynchronous external coprocessor requests that don't block Router execution, ideally as a new coprocessor stage (e.g. RouterRequestAsynchronous). 

**Describe alternatives you've considered**

- Responding to requests immediately, deferring processing to background tasks/threads. 
- Rhai. 
- Sidecar application (non-coprocessor).

**Additional context**

External coprocessing currently blocks the execution of a request until the coprocessor responds, but for some workloads (e.g. custom metrics/logging) it isn't a blocking task and the request can proceed as normal. 

For example, I need to log in a very specific format ([Bunyan](https://www.npmjs.com/package/bunyan)) that the Router doesn't support today. This log can be quick, but we still will have the overhead of HTTP regardless which can still materially affect performance. Having a way to tell the Router that "hey, this coprocessor request just needs to be sent and not block requests/cause errors on failure" would be ideal.

**Comment by garypen** [comment]
If I understand this request correctly, you are really looking for the router to support a new protocol for communication with coprocessors. An HTTP POST (which is how the router transfers data to coprocessors) requires some kind of response and the library we use for making the POST request will expect and wait for a valid HTTP POST response.

I doubt this is the kind of thing we'll be able to productise in the short term. It doesn't seem like there would be enough demand for it and if we did get a lot of demand, I'd be inclined to investigate other approaches rather than using a coprocessor (which is inherently not high performance).

In the particular use-case you mention, bunyan format logging, we could look at using `https://crates.io/crates/tracing-bunyan-formatter` to add support for bunyan format directly to the router.
