### ISSUE TITLE
Subgraph service: Don't instantiate a new pool for each request

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#3435]
We're currently recreating a connector and a pool for each subgraph_service instantiation.

We shouldn't.
While we refactor it, let's make sure we don't forget to [set a pool idle timeout duration](https://github.com/apollographql/router/pull/3434).

**Comment by garypen** [comment]
We only build a new SubgraphService at startup and during re-configuration. This is done once for each subgraph, so each subgraph has its own http client (and associated pool). We don't build a SubgraphService for each request.


We may want to modify the code so that we only have one connector/pool to share across all subgraphs, but I think it's fine to have a separate connector/pool per subgraph, since we may want to vary behaviour between subgraphs at some point.

I'll add a pool idle timeout.

**Comment by bnjjj** [comment]
@garypen I think for every request we build a new subgraph_service, look [here](https://github.com/apollographql/router/blob/dev/apollo-router/src/query_planner/fetch.rs#L249)

**Comment by bnjjj** [comment]
Ok after some investigations we don't call `SubgraphService::new` on every request we're calling the `SubgraphServiceFactory` which `clone`  the subgraph service. And cloning `hyper::Client` won't create a new pool, it's an `Arc<Mutex<>>` under the hood and so it doesn't create a new connection pool. We're good !
