### ISSUE TITLE
Subgraph level APQ should execute before AWS Sigv4 signing

### ISSUE THREAD

**Issue by Geal** [apollographql/router#3608]
Right now SigV4 signing happens as a subgraph service plugin, so before going through rhai, coprocessor and traffic shaping (dedup, timeout, retry, rate limit), and then into the subgraph service. Inside the subgraph service, there is the APQ implementation.
APQ removes the query from the body and replaces it with a hash, and if APQ is disabled by the subgraph, or not yet available in the subgraph's APQ cache, then a new request with the query is sent. Both queries will modify the body that was signed by SigV4, so signature verification will fail.
And after APQ, the body is compressed.

Here is the order that would make sense:
- deduplication
- timeout: it must cover an entire subgraph call from the point of view of the execution service, even if that means multiple subgraph calls due to retries or APQ). It could be used before deduplication, but if deduplicated queries have the same timeout, then only the first one could reach the limit
- APQ
- compression (happens before retry: no need to do that work multiple times)
- retry
- rate limiting
- AWS SigV4 (the signature holds the current time, so it must change on each retry)

Here we're reaching a design issue: we are missing a service between the subgraph service and the actual HTTP call. By separating in 2 services, we would be able to do:

- subgraph service plugin:
  - deduplication
  - timeout
  - rhai
  - coprocessor
- in subgraph service:
  - APQ
- subgraph HTTP service plugin:
  - compression
  - retry
  - rate limiting
  - AWS SigV4
- in subgraph HTTP service:
  - TLS
  - HTTP call
  
 This would require splitting some parts of the traffic shaping plugin, but at this point I feel they would live better directly in the relevant service instead of all in a layer

**Comment by Geal** [comment]
what do you have in the subgraph configuration? APQ? Compression? Header manipulation?

**Comment by grnikhil** [comment]
Below is the yaml snippet. I'm doing the header manipulation in supergraph service to add custom header but nothing in subgraph service. I checked the source code and  the authentication plugin is called immediately when request hits subgraph service and later apq/compression code is invoked. even if apq is disabled, compression still happens which mutates the request body. Service also add few headers. I think this is causing the signature mismatch when request hits aws api gateway.  I think I agree that the signing should happen just inside call_http function just before do_fetch() is invoked so that no mutation happens after signing


apq:
  enabled: false  
  subgraph:
    all:
      enabled: false

authentication:
  subgraph:
    subgraphs:
     my_subgraph_name: # configuration that will apply to all subgraphs
        aws_sig_v4:
          default_chain:
            region: "my_api_gateway_region"
            service_name: "execute-api"
            assume_role:
              role_arn:  "my_service_role_arn

**Comment by o0Ignition0o** [comment]
@grnikhil #3735 is early wip but it should fix it once it lands.
