### ISSUE TITLE
xtask: Lint import rules

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#391]
We need to have a look at the fmt rules, it seems a nightly version of fmt might allow us to enforce the "non splitting" of the imports.

```
Maybe I should have commented that more :thinking: 

As I discussed recently on our private slack channel, it's best to not try to make groups of imports at the moment. The reasoning is that these groups are subjective: I for one prefer to put the crate imports at the beginning for instance. Over time this becomes unmaintained because everybody who touch the code has no idea what is the actual grouping logic and it becomes a mix bag.

So for now please group all your `use` into a single paragraph (no newline) and let `cargo fmt` do its magic.
```

_Originally posted by @cecton in https://github.com/apollographql/router/pull/309#discussion_r797323597_

**Comment by abernix** [comment]
This is supported on `nightly` right now.  Since we're not using `nightly`, but we were tempted to use *this particular feature* I thought we could accomplish this by:

1. Introducing a `${project}/rustfmt.toml` which uses [`group_imports`](https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#group_imports):
   ```toml
   group_imports = "StdExternalCrate"
   ```
2. Introducing [a `${project}/.cargo/config.toml`](https://doc.rust-lang.org/cargo/reference/config.html#configuration) with [`alias`es](https://doc.rust-lang.org/cargo/reference/config.html#alias) defined:

   ```toml
   [alias]
   fmt = "+nightly fmt"
   ```

**Unfortunately, though:**

> **Aliases are not allowed to redefine existing built-in commands.**
