### ISSUE TITLE
Http structures improvement

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#396]
Currently structures have usability issues and are not clone.
Investigate the alternatives.

**Comment by Geal** [comment]
Summing up the issues, which are also linked to performance:
- I previously made sure the HTTP subgraph received a [url::Url](https://docs.rs/url/latest/url/struct.Url.html) at creation, because before we were passing a string, which meant invalid URLs were not detected until a subgraph call, and that string was parsed to a URL on every call
- I used this type because reqwest reexports [url::Url](https://docs.rs/reqwest/latest/src/reqwest/lib.rs.html#223)
- hyper actually uses another [Uri]https://docs.rs/http/latest/http/uri/struct.Uri.html) type, so reqwest needs to [reparse its URI then pass it to hyper](https://github.com/seanmonstar/reqwest/blob/master/src/into_url.rs#L67-L71)
- the [http crate](https://docs.rs/http) is designed to propose common types for http client and servers, but they are not very reusable, especially its own Uri type](https://docs.rs/http/latest/http/uri/struct.Uri.html) that is harder to manipulate than `url::Url`
- it's actually possible to transform from a `http Request` to a `hyper Request` using `into_parts()` then [Uri::from_parts](https://docs.rs/http/latest/src/http/uri/mod.rs.html#205-242) (or the `TryFrom` implementation)

**Comment by Geal** [comment]
the more I'm digging into this, the more I think we should keep the types from `http`, but add a usability layer above it, to make it clone, and allow easy modification of the URL

**Comment by Geal** [comment]
done in https://github.com/apollographql/router/pull/319/commits/18b7c94b46ecdd8331306c4acf96ab230c521fb4
