### ISSUE TITLE
`env::get` strips quotes from parsed environment variables

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#3979]
**Describe the bug**

When parsing an environment variable using `env::get`, it appears to strip quotes from the strings. 

Example: 

- Set an environment variable that is an array, like: `export KEYS=["1aa","ba","3ca"]` 
- P

**To Reproduce**
1. Setup services '...'
2. Submit request '....'
3. Use:

```
fn router_service(service){
    service.map_request(|request|{
        try {
            print(env::get("KEYS"));
            print(type_of(env::get("KEYS")));
}catch(err){
            log_error(err);
        }
    });
}
```

And you should see that the the string is `[1aa,ba,3ca]`. 

This leads to use-cases using JSON in environment variables needing to encode and then decode to be used. 

**Expected behavior**

Don't strip quotes. 

**Additional context**

Any changes would be breaking here, unfortunately, and given the low blast-radius it feels like documentation updates is probably the way to go.

**Comment by abernix** [comment]
It sounds like there's an expectation that an array could be an environment variable, however I'm pretty sure there's no world in which that can actually be true and is always incorrect.  That would suggest that anything other than a string would be incorrect in all cases.   It also probably very quickly gets into a world of "challenges which arise before we even get the values" because the shell itself might be doing any number of transformations on that.

I'm going to close this because I don't believe we can do anything about it, but happy to discuss if it's pressing or I missed something.  (Feel free to just re-open if you have perms.)
