### ISSUE TITLE
Docker Scout Scan

### ISSUE THREAD

**Issue by cchee** [apollographql/router#4007]
I just pull the latest docker image of the apollo graphql router (V1.32.0) and run the docker scout scan. It reports some issues, just want to see if it is being looked at.

**Comment by cchee** [comment]
I am new to graphql and apollo router, but I am willing to help if needed to build a better docker image.

**Comment by BrynCooke** [comment]
@garypen What was the outcome for this?

**Comment by peakematt** [comment]
Hi @cchee ! 

Thank you so much for your patience on this. We've reviewed the findings being generated by the `docker scout cves` command I believe you're running as well as our tooling to assess our containers. As @garypen mentioned, the primary issue we're seeing is CVE-2023-29491, a vulnerability in ncurses. We will apply the available patch for ncurses to address this vulnerability. I see that there are a handful of additional, lower-severity findings with fixes as well. We will work to get those addressed too. 

If I haven't missed anything, the remaining issues detected are all from the `debian-slim` base image the Router container uses, are low-severity, and are currently un-fixed by the Debian team. My understanding is that the Debian maintainers contest the remaining findings from the `debian-slim` base and generally consider them low risk. 

Have I missed anything though? I'm not as familiar with `docker scout cves` so I want to make sure there's not detail in a subcommand I'm missing. 

Thank you!

**Comment by cchee** [comment]
> Hi @cchee !
> 
> Thank you so much for your patience on this. We've reviewed the findings being generated by the `docker scout cves` command I believe you're running as well as our tooling to assess our containers. As @garypen mentioned, the primary issue we're seeing is [CVE-2023-29491](https://github.com/advisories/GHSA-vh2x-5rx6-qqhv), a vulnerability in ncurses. We will apply the available patch for ncurses to address this vulnerability. I see that there are a handful of additional, lower-severity findings with fixes as well. We will work to get those addressed too.
> 
> If I haven't missed anything, the remaining issues detected are all from the `debian-slim` base image the Router container uses, are low-severity, and are currently un-fixed by the Debian team. My understanding is that the Debian maintainers contest the remaining findings from the `debian-slim` base and generally consider them low risk.
> 
> Have I missed anything though? I'm not as familiar with `docker scout cves` so I want to make sure there's not detail in a subcommand I'm missing.
> 
> Thank you!

I build my own docker images for my graphql application using rust. I used alpine/latest which doesn't have any reported issue from docker scan. I am not sure if there is any plan to move to other linux distribution that is smaller and more secure. If I can be any help with this, please let me know. Thanks for looking into this and try to minimize security issue. Very much appreciated.

**Comment by abernix** [comment]
I'll close this issue for now, but we will continue to update our Docker image as much as possible as new items arise in the underlying base image.  Thanks for surfacing this originally.
