### ISSUE TITLE
Traffic routing issue in a federated GraphQL setup with multiple subgraphs.

### ISSUE THREAD

**Issue by purushottam-anand** [apollographql/router#4030]
**Describe the bug**
*Traffic routing issue in a federated GraphQL setup with multiple subgraphs.*

**To Reproduce**
*Steps to reproduce the behavior:*
1. Set up a federated GraphQL system with router and subgraphs.
2. Implement blue-green deployment for the subgraphs.
3. Shift traffic from blue stack to green stack (or vice-versa) by adjusting Route53 weights.
4. Observe the routing behavior over time.

**Expected behavior**
*We expect that after a minute, all traffic from the router should be routed to the new stack (e.g., green) due to the 60-second TTL on Route53.*

**Output**
*However, we have observed that the router continues to send requests to the old stack (e.g., blue) for a prolonged period, roughly 40-50 minutes.*

**Additional context**
*This issue raises questions about whether the router caches the subgraph's load balancer DNS or IP. If it does cache, we need to understand how to flush that cache within a minute to ensure timely traffic redirection. Is there a way to configure this behavior to align with the expected routing changes?*

**Comment by BrynCooke** [comment]
Suspect that this is connections to subgraphs are remaining open, we may need to make sure that we respect the DNS TTL.

**Comment by garypen** [comment]
I setup the following:

- a private network containing 4 systems
  - a DNS server (TTL 60)
  - router federating over 2 subgraps
  - subgraph 1
  - subgraph 2
 
I then queried the router and found that my queries resolved as expected.
I then modified my DNS configuration so that the entry for subgraph 2 pointed to a non-existing host
I then re-ran my query and found that it immediately failed because subgraph2 could not be accessed
I then restored my valid DNS configuration and re-ran the query and found that it worked fine.

I realise that this isn't the "exact" issue that is being reported by the user, but I think it's a reasonable enough approximation to show that the router is using DNS and is respecting TTL as reported by the DNS server.

@purushottam-anand It seems more likely, at this point, that there is a networking issue in your testing infrastructure. If you take the router out of the equation can you validate/confirm that your DNS server is behaving as you expect?

I'm going to mark this as blocked for now until we get concrete evidence that this is a router issue.
