### ISSUE TITLE
Inconsistent/invalid null data response when using variables

### ISSUE THREAD

**Issue by carldunham** [apollographql/router#4397]
So we are seeing an issue with nullable fields being skipped. A query like
```
query($skip: Boolean = false) {
  viewer @skip(if: $skip) {
    login
  }
}
```
returns (with variables `{"skip": true}`)
```
{
  "data": null
}
```
while 
```
query {
  viewer @skip(if: true) {
    login
  }
}
```
returns
```
{
  "data": {}
}
```
Per https://spec.graphql.org/October2021/#sec-Data:
> If an error was raised during the execution that prevented a valid response, the data entry in the response should be null.

but this does not seem to be an error case (or vars vs no vars would be equivalent). The spec is a bit vague about what happens if there is no error, but also nothing to return.
It also describes other error cases that would result in an `errors` array, and no `data` field being returned.
Not sure how all the cases would present, but certainly passing a variable shouldn't impact the ultimate return shape, I would think.

_Originally posted by @carldunham in https://github.com/apollographql/router/issues/1308#issuecomment-1855230208_

**Comment by bnjjj** [comment]
Some additional information here in order to resolve it later, but I think it might be related to the usage of [`statically_skipped`](https://github.com/apollographql/router/blob/dev/apollo-router/src/spec/selection.rs#L345:L345) method used. Because if it's not a variable we can statically remove the selection set from the execution. That's a small optimization we have in place. We might not have same behavior between the static and non static method.

**Comment by bnjjj** [comment]
@carldunham I tried to reproduce it and I wasn't able to. Could you give me example of schema to help me reproduce it ? Also your router version please. Did you try running that query on the last release ? thank you

**Comment by carldunham** [comment]
The example is from the github schema, but I can put together a stand-alone one for this. And we are using 1.33.2.
