### ISSUE TITLE
experimental_response_trace_id - provide ability for returned value to be base 10 representation of number

### ISSUE THREAD

**Issue by theJC** [apollographql/router#4422]
**Describe the solution you'd like**

Currently when using experimental_response_trace_id, the response header is a base 16 number
ie: 
`trace-id: 000000000000000000023096b9f0c199`

At Indeed we use Datadog for our APM tracing SaaS, and it deals with trace-id's in base 10 in its UI, so when pulling up a trace, the user needs to convert the trace-id from base16 to base 10 and then use that number to pull the trace up in the UI.

We would like the capability for this feature support the ability for a base 10 number to be the value returned in the header, in this case that would be:
`trace-id: 616373876212121`

**Comment by bnjjj** [comment]
A solution could be to add a new `format` configuration in `experimental_response_trace_id` that would support both `hexadecimal` and `decimal` (default set to `hexadecimal`). And we would have to check that configuration [here](https://github.com/apollographql/router/blob/2fb4c78508a69350ab7ab40f8b0575191fcedb20/apollo-router/src/plugins/telemetry/mod.rs#L477:L477) and use `t.to_u128().to_string()` instead of `t.to_string()` for `decimal` format.

What do you think about this configuration @BrynCooke ?

If you have time to open a PR @theJC I would be happy to help :)

**Comment by theJC** [comment]
Beat me to the punch! ;) Thanks @nicholascioli !
