### ISSUE TITLE
Create span for plugin init

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#4472]
Plugin log messages should be correlated for initialization.
Suggest that a span is created around the call to plugin init that contains the following attributes:

Plugin name
A version supplied by the state machine (probably a UUID).
Doing this is a central location will give all plugins better contextual information on startup.

**Comment by Geal** [comment]
so the interesting thing here is that right now we can't record spans happening on startup because the telemetry plugin is not created nor activated. It only works when reloading schema or config. On startup, we call the init_telemetry function, that creates a noop tracer:https://github.com/apollographql/router/blob/81fe06f29566402876157d0073308abd3c4f9b72/apollo-router/src/plugins/telemetry/reload.rs#L71-L79
the solution here could be to make a tracer instance that can record the spans, and once the telemetry plugin is created, we send the spans

**Comment by Geal** [comment]
or maybe, a better way would be to create and activate the telemetry plugin once, before everything is loaded

**Comment by Geal** [comment]
right, I tested in #4480 and it works well
