### ISSUE TITLE
Cannot use managed federation and layers together without specifying `router_url`

### ISSUE THREAD

**Issue by damienpontifex** [apollographql/router#522]
**Describe the bug**
Run the router with the environment variables `APOLLO_GRAPH_REF` and `APOLLO_KEY` such as to use managed federation that's setup in apollo studio. Also provide a configuration file so as to use layers and `headers_propagate` but don't set the `routing_url` as that comes from managed federation.

Running the router results in 
> Failed to read configuration: Could not deserialize configuration: subgraphs.user: missing field `routing_url` at line 12 column 11

**To Reproduce**
1. Set `APOLLO_GRAPH_REF` and `APOLLO_KEY` to appropriate values for your federated graph within apollo studio
1. Add layer configuration within configuration file to propagate headers but don't set `routing_url`
1. Run router with the flag `--configuration` pointing to a local configuration file
1. See error as described above

**Expected behavior**
Able to use apollo studio managed federation and it's configuration for routing urls but add layers for header propagation as well in the router without needing to specify the subgraph url

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.0.1

**Router version
- router 0.1.0-alpha.6

**Comment by BrynCooke** [comment]
`router_url` should disappear from the router config because it gets the URLs from the supergraph.
It was only introduced because in the early days we didn't have the ability to parse schemas and therefore could not extract the URLs. We can to this now, so it should go.
If the user want to override the URL for a subgraph they will be able to do so via a layer, this gives a consistent experience with the rest of the router functionality.
