### ISSUE TITLE
Keep router span name consistent and do not use operation name

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#5261]
## Is your feature request related to a problem? Please describe.
The span name for the service entry point for Apollo Router OpenTelemtry tracing is `<service_name>:<operation_name>`. This causes many issues with my dashboard linking in DataDog as I now have a high cardinality of spans.

![Screenshot 2024-05-28 at 2 57 58 PM](https://github.com/apollographql/router/assets/2446877/ac4d084a-2518-418f-85c2-5f4d5d137612)

![Screenshot 2024-05-28 at 2 59 04 PM](https://github.com/apollographql/router/assets/2446877/84519f83-04c0-483b-a557-bf822850f8c9)

## Describe the solution you'd like
It would be nice if instead we used just a standard name like `<serice_name>:router` or if this was configurable so I could set the span name myself. I would also like the operation name to be a configurable span attribute as I have to go to the supergraph to see this today. This is before the GraphQL parsing so what ever logic is being used to get the operation span name today should just become the attribute value

## Describe alternatives you've considered
I could maybe use a custom collector and transform all the spans

**Comment by BrynCooke** [comment]
We have followed the otel spec here: https://opentelemetry.io/docs/specs/semconv/graphql/graphql-spans/

```
The span name MUST be of the format <graphql.operation.type> <graphql.operation.name> provided that graphql.operation.type and graphql.operation.name are available. If graphql.operation.name is not available, the span SHOULD be named <graphql.operation.type>. When <graphql.operation.type> is not available, GraphQL Operation MAY be used as span name.
```

I think this would be a feature request to disable such behaviour.

**Comment by Samjin** [comment]
> For each resource, APM automatically generates a dashboard page covering:
> * Key health metrics
> * Monitor status for all monitors associated with this service
> * List of metrics for all resources associated with this service

https://docs.datadoghq.com/tracing/glossary/#resources
https://docs.datadoghq.com/tracing/services/resource_page/

Datadog requires to use static span name with `resource` and it will automatically creates APM service page and other resource pages with key metrics. Although without static name or resource, the trace would still be there, but we lost many default features from APM.

**Comment by BrynCooke** [comment]
OK, sounds like we should add the config.
For reference here is someone asking for the opposite behaviour https://github.com/apollographql/router/issues/3229.

I do think the behaviour mandated in the spec for changing the span names is really strange, and it's also noticeable that other parts of the spec don't seem to follow this pattern.

Suggest we support the following config:

```yaml
telemetry:
  instrumentation:
    spans:
      router:
        span.name: router # 

```

@bnjjj WDYT?

**Comment by bnjjj** [comment]
I agree with your solution @BrynCooke, the main reason it doesn't work today is because it's kind of an ordering rule when at the end it takes the name directly set in the span_builder [here](https://github.com/apollographql/router/blob/dev/apollo-router/src/plugins/telemetry/otel/layer.rs#L332:L332), I already have to make that kind of fix for `otel.status_code` by introducing [this](https://github.com/apollographql/router/pull/5221/files#diff-094d0ee09c48d0683b874ada1bbf28afa9423ddf9671a46dab0d35afb33efc95R31) and adding a special case [here](https://github.com/apollographql/router/pull/5221/files#diff-1cf226b78dc820b991f0c50391d7bfc2a1a60985cef9afe47fa7ecba2dceeceaR195) and [here](https://github.com/apollographql/router/pull/5221/files#diff-671f10790df0f89bcb646a9f51dca66f7873497f7dc134445ae19725998c5218R903)

**Comment by abernix** [comment]
@bnjjj and @BrynCooke  Are there implications or user-facing-observed-changes if we were to change that ordering around?
