### ISSUE TITLE
Adding possibility to clone inner service in a custom plugin

### ISSUE THREAD

**Issue by milad-habibi** [apollographql/router#657]
Hi there.
While trying to write a custom plugin,  I noticed it's not possible to clone the inner service due to usage of `BoxService` type.
There could be valid cases that it's necessary to clone the service and use it in a custom future, for example writing an authentication plugin that receives a token and validate the token by an async call to another service in the Router layer.

To improve the usability of plugins, we could also support `BoxCloneService` type in plugin Trait.

**Comment by BrynCooke** [comment]
The reason that we went for `BoxService` rather than `BoxCloneService` is that various tower layers will make Clone services non-Clone. So putting rate limiting in or any form of stateful layer will cause the user to have to deal with non clone serives.

Fortunately there is an easy fix. Use the `buffer` layer that comes with tower.

```rust
ServiceBuilder::new()
.checkpoint_async(....) <--use this layer for async stuff
.buffer(1000)
.service(service)
.boxed()
```

`buffer` will make any non-clone service clonable, and we use this internally when we need services to cross async await points.

There is a full example here:
https://github.com/apollographql/router/blob/main/examples/async-allow-client-id/src/allow_client_id_from_file.rs#L134-L141

**Comment by milad-habibi** [comment]
@BrynCooke that seems cool.I will try it out.

**Comment by BrynCooke** [comment]
Closing this issue for now. Please reopen if the example code was not sufficient to move forward.
