### ISSUE TITLE
studio: Add a UserAgent to the data submitted to the ingress.

### ISSUE THREAD

**Issue by abernix** [apollographql/router#733]
Add a UserAgent to the data submitted to the ingress.apollo-spaceport/src/server.rs:

Name to be finalised, but candidate: `ApolloRouterPluginUsageReporting`

**Comment by garypen** [comment]
@glasser Noted that the name ApolloRouterPluginUsageReporting wasn't really descriptive since the spaceport isn't a plugin: ["eh, it's not really a plugin? i think it would be fine to say apollo-spaceport or something."](https://github.com/apollographql/router/pull/309#discussion_r803160214)

There is a "standard": https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

and that seems fairly solid, I think having a version in there will pay off in the long term, so:

product: std::env!("CARGO_PKG_NAME"),
version: std::env!("CARGO_PKG_VERSION")
comment: usage reporting

which yields:
```
user-agent: apollo-spaceport / 0.1.0-preview.1 usage reporting
```
(which is consistent-ish with the header we put in the actual studio report:
```
        header.agent_version = format!(
            "{}@{}",
            std::env!("CARGO_PKG_NAME"),
            std::env!("CARGO_PKG_VERSION")
        );
```
