### ISSUE TITLE
Automated publish of docker image

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#79]
Create docker images and publish them.
Consider using https://github.com/GoogleContainerTools/distroless

**Comment by damienpontifex** [comment]
We now have the below as our docker image. I'd love any feedback on it, but also maybe include it in the repo for others to utilise. We'd love to use this as a utility vs maintaining the docker build and everything, so a published image would be nice

```dockerfile
FROM --platform=linux/amd64 debian:latest AS build

ARG ROUTER_VERSION=0.1.0-alpha.8
ADD https://github.com/apollographql/router/releases/download/v${ROUTER_VERSION}/router-${ROUTER_VERSION}-x86_64-linux.tar.gz /tmp/router.tar.gz

WORKDIR /tmp
RUN tar xvzf router.tar.gz

FROM --platform=linux/amd64 gcr.io/distroless/base-debian11

COPY --from=build /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/lib/x86_64-linux-gnu/
COPY --from=build /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/

COPY --from=build /tmp/dist/router .
COPY configuration.yaml .

CMD ["./router", "--config", "configuration.yaml"]
```

_All the `--platform=linux/amd64` is because of macOS m1 build and making it work there. I don't think it has any effect when running on linux anyway, so just opens up ability to run on docker for mac without issue_

**Comment by BrynCooke** [comment]
Note that if you are running in kubernetes and are mounting the config file via config map then it is well worth adding the `--watch` flag to enable hot reload on config change.
