### ISSUE TITLE
tests: subgraph service mock panics don't fail tests

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#878]
As shown in [this pull request](https://github.com/apollographql/router/pull/873) panics that happen within a subgraph service implementation aren't propagated to the test harness.

Further investigation is required to know if panics would be silenced in production code (there is no panic in our subgraph service implementation)

Expected:
Tests that panic within autmock's `withf` method trigger a test failure
Actual:
They currently don't

A failing test can be found in the [igni/withf_panic_test](https://github.com/apollographql/router/tree/igni/withf_panic_test) branch.

Note the test does panic if run if the `failfast` feature is enabled, but it's not the expected message.

**Comment by garypen** [comment]
Because the panic is handled in the call stack, this doesn't result in a panic (so tests shouldn't expect to panic), but results in an error. In this particular case, the query_planner detects that the subgraph invocation has failed and generates an error response, looking something like:
```
errors: [Error { message: "HTTP fetch failed from 'product': service closed", locations: [], path: Some(Path([])), extensions: {"type": String("SubrequestHttpError"), "service": String("product"), "reason": String("service closed")} }]
```
Note: the HTTP fetch failed with a reason of "service closed".

This means a test that includes a panic in a subgraph fetch, should expect a result with an error with a reason of "service closed". I'll add a test with some comments that illustrates this.

**Comment by bnjjj** [comment]
I don't know if it's related or not but I discovered recently when running this command: `cargo test --package apollo-router-core --lib --target-dir ./.cargo_check -- query_planner::tests --nocapture` I saw some ignored panics in logs
