### ISSUE TITLE
Finalize migration from Warp to Axum

### ISSUE THREAD

**Issue by abernix** [apollographql/router#902]
Currently, both Warp and Axum are both still participants in the project as web frameworks.  Let's finalize the migration by:

- [x] Adding more Axum tests (at least as many as we had for Warp, maybe more?)
- [ ] Removing Warp from the project as a feature since it's no longer being actively added to
- [ ] Add lists of tests we want to have

**Comment by bnjjj** [comment]
Here is a list of tests I would like to add in order to be more confident with our migration:

- [ ] Http request with unsupported `Content-Type` header
- [ ] Test homepage with the option to disable landing page
- [ ] Test the shape of `originating_request` (headers, url, body, method) in `RouterRequest` when we do a `GET` and a `POST` request, on different paths (`/` and `/graphql`).
- [ ] Do these tests also for unix socket
- [ ] Test `custom_endpoint` with a fake plugin
