### ISSUE TITLE
Fragments on interfaces don't work.

### ISSUE THREAD

**Issue by Mithras** [apollographql/router#928]
**Describe the bug**
Fragments on interfaces don't work.

**To Reproduce**
```
query {
  # [MyInterface!]!
  test {
    fieldA
    ... on MyInterface {
      fieldB
    }
    ... on MyActualType {
      fieldC
    }
  }
}
```

**Expected behavior**
The query above should always return `fieldA` and `fieldB`, and `fieldC` only for `MyActualType`.

**Actual behavior**
`fieldB` is never returned.

**Desktop (please complete the following information):**
`ghcr.io/apollographql/router:v0.1.0-preview.6`

**Comment by DoumanAsh** [comment]
@bnjjj I copy my comment from discussion since I also discovered the same issue
It is wrapper over `apollo-router-core` which provides simplified interface with ability to use `async-graphql` schema inside embedded router https://github.com/DoumanAsh/graphql-router-example

We see the same issue with latest preview of `apollo-router` as separate binary too

Here is my test example as PR https://github.com/DoumanAsh/graphql-router-example/pull/1

It is present on branch: `broken_fragment`

Revision of `apollo-router-core` is `86e77965b536bfded97f6ef9687096eb2c520026`

Here is supergraph schema generated by Rover https://github.com/DoumanAsh/graphql-router-example/blob/broken_fragment/tests/supergraph.graphql

Here is `UserType` interface alongside concrete impementations:
https://github.com/DoumanAsh/graphql-router-example/blob/broken_fragment/tests/user.graphql#L5-L10=
https://github.com/DoumanAsh/graphql-router-example/blob/broken_fragment/tests/user.graphql#L15-L17=

My query:
https://github.com/DoumanAsh/graphql-router-example/blob/broken_fragment/tests/router.rs#L343-L354=

```
    fragment TypeBase on UserType {
      __typename
      description
    }
    query Query {
      meType {
        ...TypeBase
      }
    }
```

Its result is empty:
```
{
  "data": {
    "meType": {
       }
    }
}
```

But if I inline fragment into query I get proper output:
```
{
  "data": {
     "meType": {
       "__typename": "RegularUser",
       "description":"regular"
     }
    }
}
```

I added log to my subgraph implementation to see what query comes from supergraph:

```
query Query__user__0{meType{__typename ...on RegularUser{__typename description}...on SuperUser{__typename description}}}
```

In case of inlined fragment seems to be the same

```
query Query__user__0{meType{__typename ...on RegularUser{__typename description}...on SuperUser{__typename description}}}
````

In case you're in doubt about my code.
My subgraph correctly returns:

```
{"data":{"meType":{"__typename":"RegularUser","description":"regular"}}}
```

**Comment by DoumanAsh** [comment]
@bnjjj I think I have some idea on what is wrong.
So when router service gets output, it needs to format it according to query.
In case of normal query without fragments, we just go through fields and apply them as it is.
But in case of fragment logic is more complicated,  before it would apply fragment content it checks whether returned type corresponds to fragment's type

https://github.com/apollographql/router/blob/main/apollo-router-core/src/spec/query.rs#L445-L450=

This logic is correct for when fragment is for concrete type, but I don't think it is applicable for when fragment targets interface?

**Comment by DoumanAsh** [comment]
I made PR to fix the issue by changing condition of formatting output to check whether fragment is for interface or not https://github.com/apollographql/router/pull/949

If interface has implementation for type, then it is applied otherwise we just skip it
