### ISSUE TITLE
Router plugin declares new graphql endpoint

### ISSUE THREAD

**Issue by yanns** [apollographql/router#933]
**The problem**
You are operation a multi-tenant GraphQL endpoint. To distinguish between tenants, we have a graphql endpoint in the form of `<project key>/graphql`.
We are in the process of integrating GraphQL federation in our system.

We are trying out this router. We have not found any possibility to customize the path of the graphql endpoint.

**Describe the solution you'd like**
A plugin could declare new graphql endpoints.
For the current endpoints (`/` and `/graphql`), it could override the responses:
- for `/` a simple 200. 
- for `graphql`, a 404.

**Describe alternatives you've considered**
(1) We can add another component before the router that transforms the request into `/graphql` and propagates the `<project key>` as a header for example. Then in the router, a plugin transform the url `SubgraphRequest` into `<project key>/graphql`.
This would involve one component more, and be less reliable.

(2) instead of calling `apollo::main`, we could call another function that allows to change the endpoints. This would be another API for the router that needs to be maintained.

(3) copy-paste `apollo::main` into our `main` and modify per hand what needs to be modified. With that approach, we need to make much more structures public so that this can compile. And it's more difficult to catch with upstream changes.

**Comment by BrynCooke** [comment]
Current thinking is that:
1. We should reduce from 2 to 1 paths
1. Path should default to `/`
1. The default should be strict, meaning `/jjjj` should not just work because `/` is configured.
1. You can configure it to be something else with path e.g. `/graphql`.
1. You can allow `/graphql/*` by specifying path: `/graphql/*`
1. The thing printed to the console at startup uses path.

Configuration would be in the server section for the yaml.

**Comment by yanns** [comment]
It sounds good.
We also need to support `<project key>/graphql` and `<project key>/graphql/`.

**Comment by BrynCooke** [comment]
@yanns Can you clarify, are you aiming to run multiple instance of the router on one box? Or trying to run multiple instances of the router in once process?

The latter is probably a no-go because tokio tracing and otel make extensive use of global variables, and things will get messy. 

On the other hand if you are looking to run multiple processes we could enable you to use environment variable expansion in the server section of the config and thus enable you to achieve what you want as long as you specify `<project key>` as an env variable before startup.
