### ISSUE TITLE
Configuration environment expansion should happen sooner

### ISSUE THREAD

**Issue by damienpontifex** [apollographql/router#969]
**Is your feature request related to a problem? Please describe.**
Problem running router "out of the box" in stateless hosting. 

A few hosting solutions are stateless by default and so configuration overriding with the config file is sometimes difficult to achieve. The current codes default, as below, binds to `127.0.0.1` and so solutions like Kubernetes we've had to override the configuration to bind it to `0.0.0.0` to make it work (doable, but would be nice to not have to by default)

On the port side, some examples of providers exposing the port to the application through the `PORT` environment variable e.g. [Cloud Run](https://cloud.google.com/run/docs/container-contract#port), and I've known azure app service to do the same. 

Current default:

https://github.com/apollographql/router/blob/d13998f35315675a4ed00d118adc283d50345d3d/apollo-router/src/configuration/mod.rs#L86-L88

**Describe the solution you'd like**
Listen to _unspecified_ or `0.0.0.0` and utilise `PORT` environment variable if set of default back to 4000 as the current default. For example, proposed function for the same thing below:
```rust
fn default_listen() -> ListenAddr {
    let port: u16 = std::env::var("PORT").ok()
        .and_then(|p| p.parse().ok())
        .unwrap_or(4000);
    SocketAddr::from((std::net::Ipv4Addr::UNSPECIFIED, port)).into()
}
```

**Describe alternatives you've considered**
- Can be overridden in the configuration file, but loading the configuration file in a stateless hosting such as Cloud Run is not as supported
- Run in non-stateless hosting (e.g. cloud run on anthos) and utilise ConfigMaps to host the configuration file
- Build custom docker image, with public router image as base, where we add in the configuration yaml file into the image so we can have config like `listen: 0.0.0.0:${PORT}` within that image to run on services like Cloud Run without needing to mount the file externally (might have to do this anyway to override other configuration we'd need in config file to run in the stateless Cloud Run environment)

**Comment by abernix** [comment]
Thanks for opening this conversation!  We're definitely interested in simplifying the adoption story in the general sense.  Practically speaking, I'd claim there are two different issues in this issue right now:

1. default bind address
2. `PORT` support

These seem deserving of different conversations and different PRs since I can see them landing separately and having different levels of scrutiny applied to them.  Thoughts on breaking these apart?

**Comment by abernix** [comment]
Briefly, for the `PORT` configuration part of this: that seems like a very reasonable consideration, though I might claim best to implement at the container image (e.g., Docker) level rather than natively in the `router` since the Router might be running on the same host that sets a `PORT` for another reason (e.g., running two things in the same environment).  It would be reasonable to, for example, have a run-script for the `router` in a Docker image automatically interpolate `PORT` into a start-up configuration?

**Comment by abernix** [comment]
Separately, binding to `0.0.0.0` does not seem like a safe and secure default and in my experience is commonly the source of misconfiguration/risk since it binds to all interfaces which — while potentially ideal for your case — would also bind to the public interface when running the `router` on, e.g., my laptop, or on a host with multiple interfaces, some public and some private.  I'd claim that this is the reason that it exists in the state that it's in today is for security and further claim that it's a more common pattern to opt-into binding to all-interfaces rather than the default.

**Comment by Geal** [comment]
a side point here on the beginning experience with the router:
- it shows the listening address on startup
- opening that address will redirect to Apollo Studio, connecting to that address
- Studio will not do queries to `http://0.0.0.0:4000` for security reasons. `127.0.0.1:4000` is fine, but there's nothing explaining why we should not use `0.0.0.0`

**Comment by damienpontifex** [comment]
@abernix brilliant explanation and thought process of these considerations. Thank you. Very happy to break it up as needed and happy to be able to contribute on the adoption process.

Currently I shifted to a new docker image that is to copy in my router config so I overcome any of these issues I had running on cloud run.
```dockerfile
ARG VERSION=v0.1.0-preview.7
FROM ghcr.io/apollographql/router:${VERSION}

COPY router-config.yaml /etc/router/
ENV CONFIGURATION_PATH=/etc/router/router-config.yaml
```

Overall though, I'd love to be able to use the router as a "utility" and use the public image, so very open to feedback on better ways or trialling any suggestions and providing any feedback I can to improve this space

**Comment by BrynCooke** [comment]
Just adding some more context. We would like to avoid proliferation of environment variables in the router if at all possible. Typically these things accumulate over time in an incoherent fashion, and can bite users and developers when they forget that they set something in the environment.

To this end, most of the config file supports [environment variable expansion](https://www.apollographql.com/docs/router/configuration/overview#environment-variable-expansion). This doesn't currently apply to the `server` section of the yaml, but will eventually be added. By looking at the config file it is clear to the users what values are coming from their environment. It also means that configuration logic stays centralised rather than scattered across the codebase. 

Once expansion for the `server` section is in place maybe the default config shipped with our docker containers contains something like this: 
```
server:
  listen: "${APOLLO_ROUTER_SERVER_LISTEN:127.0.0.1:4000}"
```

**Comment by o0Ignition0o** [comment]
Let's document the current behavior and how it can be customized
