### ISSUE TITLE
plugin pipeline streamlining

### ISSUE THREAD

**Issue by garypen** [apollographql/router#980]
**Describe the solution you'd like**

During the course of re-working the `Rhai` plugin, I've noticed that there is a significant amount of naming and structure "variability" which makes it hard to perform "generic" handling for components. The types of variations are (mainly) I expect justifiable, but certainly some aren't and so we should seek to reduce arbitrary variations to simplify programming.

Here are some examples which we need to consider:

 - naming: plugin_steps tend to follow the name of the structure they represent. In itself, that is probably a decision worth re-considering, but given that is the case, then "query_planner" to "query_planning" seems like a mistake. We should rename the "query_planning_service" to be "query_planner_service".
 - Some data is contained within an `Arc` (e.g. `variables` on the `Request`). Is this for performance reasons or to prevent users from interacting with this data? In general, we should consider these kind of things carefully.
 - Some data doesn't really make sense to interact with at certain stages in the pipeline. For example: If you try altering a `Request.query` *after* the `QueryPlanner` step what would you expect to happen? Should we (somehow) enforce logical constraints like this?
 - How do we propagate subgraph header responses back to the client? (I think there's already an issue for this)
 - Variations in <type>Response.response data type.  Usually `Response` but RouterResponse has `ResponseBody`.
 - No way to propagate errors at the QueryPlan stage.

This list isn't exhaustive, but it's reasonably indicative of the types of things we should consider.

**Describe alternatives you've considered**

Leave things as they are.

**Additional context**

N/A

**Comment by SimonSapin** [comment]
> This list isn't exhaustive, but it's reasonably indicative of the types of things we should consider.

Yes, absolutely. Still, on the specific items raised here:

* We renamed `query_planning_service` to `query_planner_service`
* I don’t see an `Arc` in `apollo_router::graphql::Request`, maybe it was removed since this issue was opened? Are there other cases of maybe-unnecessary `Arc`s?
* Maybe this kind of thing should be addressed in the documentation for the different pipeline stages?
* Subgraph response header propagation is tracked at https://github.com/apollographql/router/issues/1284
* `ResponseBody` is gone. The response types are still not uniform (see below), but for reasons that make sense to me
* Query planner error handling is tracked at https://github.com/apollographql/router/issues/1142

---

Response types:

```rust
pub struct SupergraphResponse {
    pub response: http_ext::Response<BoxStream<'static, graphql::Response>>,
    pub context: Context,
}

pub struct QueryPlannerResponse {
    pub(crate) content: QueryPlannerContent,
    pub context: Context,
}

pub struct ExecutionResponse {
    pub response: http_ext::Response<BoxStream<'static, graphql::Response>>,
    pub context: Context,
}

pub struct SubgraphResponse {
    pub response: http_ext::Response<graphql::Response>,
    pub context: Context,
}

```

**Comment by garypen** [comment]
I removed the `Arc` from `variables` in a previous PR: #1257. I don't think there are other unnecessary `Arc`s.

I think your other comments on issues related here make perfect sense and the separate tracking of the remaining issues means I'm happy to close this down.
